/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "arbitro1Synth.v:1" *)
module arbitro1Synth(reset, clk, emptyFIFO, almost_fullFIFO, pop, push);
  (* src = "arbitro1Synth.v:40" *)
  wire [2:0] _000_;
  (* src = "arbitro1Synth.v:40" *)
  wire [2:0] _001_;
  (* src = "arbitro1Synth.v:40" *)
  wire [2:0] _002_;
  (* src = "arbitro1Synth.v:40" *)
  wire [2:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  (* src = "arbitro1Synth.v:4" *)
  input [3:0] almost_fullFIFO;
  (* src = "arbitro1Synth.v:2" *)
  input clk;
  (* src = "arbitro1Synth.v:8" *)
  wire [2:0] contadorP0;
  (* src = "arbitro1Synth.v:8" *)
  wire [2:0] contadorP1;
  (* src = "arbitro1Synth.v:8" *)
  wire [2:0] contadorP2;
  (* src = "arbitro1Synth.v:8" *)
  wire [2:0] contadorP3;
  (* src = "arbitro1Synth.v:3" *)
  input [3:0] emptyFIFO;
  (* src = "arbitro1Synth.v:5" *)
  output [3:0] pop;
  (* src = "arbitro1Synth.v:6" *)
  output [3:0] push;
  (* src = "arbitro1Synth.v:2" *)
  input reset;
  NOT _085_ (
    .A(contadorP2[1]),
    .Y(_029_)
  );
  NOT _086_ (
    .A(contadorP1[0]),
    .Y(_030_)
  );
  NOT _087_ (
    .A(contadorP0[0]),
    .Y(_031_)
  );
  NOT _088_ (
    .A(contadorP0[1]),
    .Y(_032_)
  );
  NOT _089_ (
    .A(contadorP0[2]),
    .Y(_033_)
  );
  NOT _090_ (
    .A(reset),
    .Y(_034_)
  );
  NOT _091_ (
    .A(emptyFIFO[0]),
    .Y(_035_)
  );
  NAND _092_ (
    .A(contadorP1[0]),
    .B(contadorP1[1]),
    .Y(_036_)
  );
  NOR _093_ (
    .A(contadorP1[2]),
    .B(emptyFIFO[1]),
    .Y(_037_)
  );
  NAND _094_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  NOT _095_ (
    .A(_038_),
    .Y(_039_)
  );
  NOR _096_ (
    .A(almost_fullFIFO[2]),
    .B(almost_fullFIFO[3]),
    .Y(_040_)
  );
  NOR _097_ (
    .A(almost_fullFIFO[0]),
    .B(almost_fullFIFO[1]),
    .Y(_041_)
  );
  NAND _098_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  NOT _099_ (
    .A(_042_),
    .Y(_043_)
  );
  NOR _100_ (
    .A(contadorP0[2]),
    .B(emptyFIFO[0]),
    .Y(_044_)
  );
  NAND _101_ (
    .A(_033_),
    .B(_035_),
    .Y(_045_)
  );
  NOR _102_ (
    .A(_042_),
    .B(_044_),
    .Y(_046_)
  );
  NAND _103_ (
    .A(_043_),
    .B(_045_),
    .Y(_047_)
  );
  NOR _104_ (
    .A(_038_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _105_ (
    .A(_039_),
    .B(_046_),
    .Y(_049_)
  );
  NAND _106_ (
    .A(_030_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _107_ (
    .A(contadorP3[0]),
    .B(contadorP3[1]),
    .Y(_051_)
  );
  NOT _108_ (
    .A(_051_),
    .Y(_052_)
  );
  NOR _109_ (
    .A(contadorP3[2]),
    .B(emptyFIFO[3]),
    .Y(_053_)
  );
  NOT _110_ (
    .A(_053_),
    .Y(_054_)
  );
  NOR _111_ (
    .A(_052_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _112_ (
    .A(contadorP2[1]),
    .B(contadorP2[2]),
    .Y(_056_)
  );
  NOT _113_ (
    .A(_056_),
    .Y(_057_)
  );
  NOR _114_ (
    .A(emptyFIFO[2]),
    .B(_057_),
    .Y(_058_)
  );
  NOR _115_ (
    .A(_055_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _116_ (
    .A(_039_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _117_ (
    .A(contadorP1[0]),
    .B(_046_),
    .Y(_061_)
  );
  NOR _118_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  NAND _119_ (
    .A(reset),
    .B(_050_),
    .Y(_063_)
  );
  NOR _120_ (
    .A(_062_),
    .B(_063_),
    .Y(_001_[0])
  );
  NOR _121_ (
    .A(_038_),
    .B(_061_),
    .Y(_064_)
  );
  NOR _122_ (
    .A(contadorP1[1]),
    .B(_064_),
    .Y(_065_)
  );
  NAND _123_ (
    .A(_038_),
    .B(_059_),
    .Y(_066_)
  );
  NAND _124_ (
    .A(_038_),
    .B(_046_),
    .Y(_067_)
  );
  NOT _125_ (
    .A(_067_),
    .Y(_068_)
  );
  NAND _126_ (
    .A(_059_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _127_ (
    .A(reset),
    .B(_069_),
    .Y(_070_)
  );
  NOR _128_ (
    .A(_065_),
    .B(_070_),
    .Y(_001_[1])
  );
  NAND _129_ (
    .A(_046_),
    .B(_059_),
    .Y(_071_)
  );
  NAND _130_ (
    .A(contadorP1[2]),
    .B(_071_),
    .Y(_072_)
  );
  NOR _131_ (
    .A(_034_),
    .B(_072_),
    .Y(_001_[2])
  );
  NAND _132_ (
    .A(_045_),
    .B(_060_),
    .Y(_073_)
  );
  NAND _133_ (
    .A(contadorP3[0]),
    .B(_067_),
    .Y(_074_)
  );
  NAND _134_ (
    .A(_073_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _135_ (
    .A(_042_),
    .B(_058_),
    .Y(_076_)
  );
  NOR _136_ (
    .A(contadorP3[0]),
    .B(_076_),
    .Y(_077_)
  );
  NAND _137_ (
    .A(reset),
    .B(_075_),
    .Y(_078_)
  );
  NOR _138_ (
    .A(_077_),
    .B(_078_),
    .Y(_003_[0])
  );
  NOR _139_ (
    .A(_058_),
    .B(_067_),
    .Y(_079_)
  );
  NOT _140_ (
    .A(_079_),
    .Y(_080_)
  );
  NAND _141_ (
    .A(contadorP3[1]),
    .B(reset),
    .Y(_081_)
  );
  NOR _142_ (
    .A(_079_),
    .B(_081_),
    .Y(_003_[1])
  );
  NAND _143_ (
    .A(contadorP3[2]),
    .B(reset),
    .Y(_082_)
  );
  NOR _144_ (
    .A(_079_),
    .B(_082_),
    .Y(_003_[2])
  );
  NAND _145_ (
    .A(contadorP2[0]),
    .B(_058_),
    .Y(_083_)
  );
  NOR _146_ (
    .A(_067_),
    .B(_083_),
    .Y(_084_)
  );
  NOT _147_ (
    .A(_084_),
    .Y(_004_)
  );
  NAND _148_ (
    .A(_069_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _149_ (
    .A(reset),
    .B(_058_),
    .Y(_006_)
  );
  NOR _150_ (
    .A(_067_),
    .B(_006_),
    .Y(pop[2])
  );
  NAND _151_ (
    .A(contadorP2[0]),
    .B(reset),
    .Y(_007_)
  );
  NOT _152_ (
    .A(_007_),
    .Y(_008_)
  );
  NOR _153_ (
    .A(pop[2]),
    .B(_008_),
    .Y(_009_)
  );
  NOR _154_ (
    .A(_005_),
    .B(_009_),
    .Y(_002_[0])
  );
  NOR _155_ (
    .A(_055_),
    .B(_067_),
    .Y(_010_)
  );
  NOR _156_ (
    .A(_029_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _157_ (
    .A(_084_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _158_ (
    .A(_034_),
    .B(_012_),
    .Y(_002_[1])
  );
  NAND _159_ (
    .A(contadorP2[2]),
    .B(reset),
    .Y(_013_)
  );
  NOR _160_ (
    .A(_010_),
    .B(_013_),
    .Y(_002_[2])
  );
  NAND _161_ (
    .A(_043_),
    .B(_044_),
    .Y(_014_)
  );
  NOT _162_ (
    .A(_014_),
    .Y(_015_)
  );
  NAND _163_ (
    .A(_031_),
    .B(_014_),
    .Y(_016_)
  );
  NOR _164_ (
    .A(_031_),
    .B(_014_),
    .Y(_017_)
  );
  NAND _165_ (
    .A(contadorP0[0]),
    .B(_015_),
    .Y(_018_)
  );
  NAND _166_ (
    .A(_016_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _167_ (
    .A(_070_),
    .B(_019_),
    .Y(_000_[0])
  );
  NOR _168_ (
    .A(_032_),
    .B(_018_),
    .Y(_020_)
  );
  NAND _169_ (
    .A(contadorP0[1]),
    .B(_017_),
    .Y(_021_)
  );
  NAND _170_ (
    .A(_032_),
    .B(_018_),
    .Y(_022_)
  );
  NAND _171_ (
    .A(_021_),
    .B(_022_),
    .Y(_023_)
  );
  NOR _172_ (
    .A(_070_),
    .B(_023_),
    .Y(_000_[1])
  );
  NOR _173_ (
    .A(_042_),
    .B(_066_),
    .Y(_024_)
  );
  NOR _174_ (
    .A(_033_),
    .B(_024_),
    .Y(_025_)
  );
  NOR _175_ (
    .A(_020_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _176_ (
    .A(_034_),
    .B(_026_),
    .Y(_000_[2])
  );
  NOR _177_ (
    .A(_034_),
    .B(_014_),
    .Y(pop[0])
  );
  NAND _178_ (
    .A(reset),
    .B(_048_),
    .Y(_027_)
  );
  NOT _179_ (
    .A(_027_),
    .Y(pop[1])
  );
  NAND _180_ (
    .A(reset),
    .B(_055_),
    .Y(_028_)
  );
  NOR _181_ (
    .A(_080_),
    .B(_028_),
    .Y(pop[3])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _182_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contadorP0[0])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _183_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contadorP0[1])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _184_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contadorP0[2])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _185_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contadorP1[0])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _186_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contadorP1[1])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _187_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contadorP1[2])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _188_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contadorP2[0])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _189_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contadorP2[1])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _190_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contadorP2[2])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _191_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contadorP3[0])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _192_ (
    .C(clk),
    .D(_003_[1]),
    .Q(contadorP3[1])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _193_ (
    .C(clk),
    .D(_003_[2]),
    .Q(contadorP3[2])
  );
  assign push = pop;
endmodule
