/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "controlSynth.v:1" *)
module controlSynth(full_umbral, empty_umbral, clk, reset, fifoSynth_wr, fifo_rd, almost_empty, almost_full, full, empty);
  (* src = "controlSynth.v:8" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  (* src = "controlSynth.v:4" *)
  output almost_empty;
  (* src = "controlSynth.v:4" *)
  output almost_full;
  (* src = "controlSynth.v:3" *)
  input clk;
  (* src = "controlSynth.v:6" *)
  wire [2:0] contador;
  (* src = "controlSynth.v:4" *)
  output empty;
  (* src = "controlSynth.v:2" *)
  input [2:0] empty_umbral;
  (* src = "controlSynth.v:3" *)
  input fifoSynth_rd;
  (* src = "controlSynth.v:3" *)
  input fifoSynth_wr;
  (* src = "controlSynth.v:4" *)
  output full;
  (* src = "controlSynth.v:2" *)
  input [2:0] full_umbral;
  (* src = "controlSynth.v:3" *)
  input reset;
  NOT _43_ (
    .A(contador[0]),
    .Y(_01_)
  );
  NOT _44_ (
    .A(contador[1]),
    .Y(_02_)
  );
  NOT _45_ (
    .A(contador[2]),
    .Y(_03_)
  );
  NOT _46_ (
    .A(reset),
    .Y(_04_)
  );
  NOT _47_ (
    .A(fifoSynth_rd),
    .Y(_05_)
  );
  NOT _48_ (
    .A(full_umbral[0]),
    .Y(_06_)
  );
  NOT _49_ (
    .A(full_umbral[1]),
    .Y(_07_)
  );
  NOT _50_ (
    .A(full_umbral[2]),
    .Y(_08_)
  );
  NOT _51_ (
    .A(empty_umbral[1]),
    .Y(_09_)
  );
  NOT _52_ (
    .A(empty_umbral[2]),
    .Y(_10_)
  );
  NOR _53_ (
    .A(_03_),
    .B(full_umbral[2]),
    .Y(_11_)
  );
  NOR _54_ (
    .A(contador[2]),
    .B(_08_),
    .Y(_12_)
  );
  NOR _55_ (
    .A(_02_),
    .B(full_umbral[1]),
    .Y(_13_)
  );
  NOR _56_ (
    .A(contador[1]),
    .B(_07_),
    .Y(_14_)
  );
  NOR _57_ (
    .A(contador[0]),
    .B(_06_),
    .Y(_15_)
  );
  NOR _58_ (
    .A(_14_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _59_ (
    .A(_13_),
    .B(_16_),
    .Y(_17_)
  );
  NOR _60_ (
    .A(_12_),
    .B(_17_),
    .Y(_18_)
  );
  NOR _61_ (
    .A(_11_),
    .B(_18_),
    .Y(_19_)
  );
  NAND _62_ (
    .A(reset),
    .B(_19_),
    .Y(_20_)
  );
  NOR _63_ (
    .A(contador[2]),
    .B(_10_),
    .Y(_21_)
  );
  NOR _64_ (
    .A(contador[1]),
    .B(_09_),
    .Y(_22_)
  );
  NOR _65_ (
    .A(_02_),
    .B(empty_umbral[1]),
    .Y(_23_)
  );
  NOR _66_ (
    .A(_01_),
    .B(empty_umbral[0]),
    .Y(_24_)
  );
  NOR _67_ (
    .A(_23_),
    .B(_24_),
    .Y(_25_)
  );
  NOR _68_ (
    .A(_22_),
    .B(_25_),
    .Y(_26_)
  );
  NOR _69_ (
    .A(_03_),
    .B(empty_umbral[2]),
    .Y(_27_)
  );
  NOR _70_ (
    .A(_26_),
    .B(_27_),
    .Y(_28_)
  );
  NOR _71_ (
    .A(_21_),
    .B(_28_),
    .Y(_29_)
  );
  NOR _72_ (
    .A(_20_),
    .B(_29_),
    .Y(almost_empty)
  );
  NOR _73_ (
    .A(_04_),
    .B(_19_),
    .Y(almost_full)
  );
  NOR _74_ (
    .A(contador[0]),
    .B(contador[1]),
    .Y(_30_)
  );
  NAND _75_ (
    .A(_03_),
    .B(_30_),
    .Y(_31_)
  );
  NOR _76_ (
    .A(_20_),
    .B(_31_),
    .Y(full)
  );
  NOR _77_ (
    .A(_01_),
    .B(fifoSynth_rd),
    .Y(_32_)
  );
  NOR _78_ (
    .A(contador[0]),
    .B(_05_),
    .Y(_33_)
  );
  NAND _79_ (
    .A(_01_),
    .B(fifoSynth_rd),
    .Y(_34_)
  );
  NOR _80_ (
    .A(_32_),
    .B(_33_),
    .Y(_35_)
  );
  NOR _81_ (
    .A(_04_),
    .B(_35_),
    .Y(_00_[0])
  );
  NAND _82_ (
    .A(fifoSynth_rd),
    .B(_30_),
    .Y(_36_)
  );
  NAND _83_ (
    .A(contador[1]),
    .B(_34_),
    .Y(_37_)
  );
  NAND _84_ (
    .A(_36_),
    .B(_37_),
    .Y(_38_)
  );
  NAND _85_ (
    .A(reset),
    .B(_38_),
    .Y(_39_)
  );
  NOT _86_ (
    .A(_39_),
    .Y(_00_[1])
  );
  NOR _87_ (
    .A(_03_),
    .B(_36_),
    .Y(_40_)
  );
  NAND _88_ (
    .A(_03_),
    .B(_36_),
    .Y(_41_)
  );
  NAND _89_ (
    .A(reset),
    .B(_41_),
    .Y(_42_)
  );
  NOR _90_ (
    .A(_40_),
    .B(_42_),
    .Y(_00_[2])
  );
  (* src = "controlSynth.v:8" *)
  DFF _91_ (
    .C(clk),
    .D(_00_[0]),
    .Q(contador[0])
  );
  (* src = "controlSynth.v:8" *)
  DFF _92_ (
    .C(clk),
    .D(_00_[1]),
    .Q(contador[1])
  );
  (* src = "controlSynth.v:8" *)
  DFF _93_ (
    .C(clk),
    .D(_00_[2]),
    .Q(contador[2])
  );
  assign empty = 1'h0;
endmodule

(* top =  1  *)
(* src = "fifoSynth.v:6" *)
module fifoSynth(fifo_in, full_umbral, empty_umbral, clk, reset, fifo_wr, fifo_rd, almost_full, almost_empty, full, empty, fifo_out);
  (* src = "fifoSynth.v:10" *)
  output almost_empty;
  (* src = "fifoSynth.v:10" *)
  output almost_full;
  (* src = "fifoSynth.v:9" *)
  input clk;
  (* src = "fifoSynth.v:10" *)
  output empty;
  (* src = "fifoSynth.v:8" *)
  input [2:0] empty_umbral;
  (* src = "fifoSynth.v:7" *)
  input [11:0] fifoSynth_in;
  (* src = "fifoSynth.v:11" *)
  output [11:0] fifoSynth_out;
  (* src = "fifoSynth.v:9" *)
  input fifoSynth_rd;
  (* src = "fifoSynth.v:9" *)
  input fifoSynth_wr;
  (* src = "fifoSynth.v:10" *)
  output full;
  (* src = "fifoSynth.v:8" *)
  input [2:0] full_umbral;
  (* src = "fifoSynth.v:13" *)
  wire [2:0] rd_ptr;
  (* src = "fifoSynth.v:9" *)
  input reset;
  (* src = "fifoSynth.v:13" *)
  wire [2:0] wr_ptr;
  (* module_not_derived = 32'd1 *)
  (* src = "fifoSynth.v:43" *)
  controlSynth controllog (
    .almost_empty(almost_empty),
    .almost_full(almost_full),
    .clk(clk),
    .empty(empty),
    .empty_umbral(empty_umbral),
    .fifoSynth_rd(fifo_rd),
    .fifoSynth_wr(fifo_wr),
    .full(full),
    .full_umbral(full_umbral),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifoSynth.v:15" *)
  memoriaSynth memoriaFIFO (
    .clk(clk),
    .data(fifoSynth_in),
    .q(fifoSynth_out),
    .rd_ptr(rd_ptr),
    .readSynth(fifoSynth_rd),
    .reset(reset),
    .wr_ptr(wr_ptr),
    .writeSynth(fifoSynth_wr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifoSynth.v:35" *)
  readSynth readlog (
    .clk(clk),
    .fifoSynth_rd(fifo_rd),
    .rd_ptr(rd_ptr),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifoSynth.v:27" *)
  writeSynth writelog (
    .clk(clk),
    .fifoSynth_wr(fifo_wr),
    .reset(reset),
    .wr_ptr(wr_ptr)
  );
endmodule

(* src = "memoriaSynth.v:1" *)
module memoriaSynth(data, wr_ptr, rd_ptr, writeSynth, readSynth, clk, reset, q);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire _0760_;
  wire _0761_;
  wire _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  wire _0767_;
  wire _0768_;
  wire _0769_;
  wire _0770_;
  wire _0771_;
  wire _0772_;
  wire _0773_;
  wire _0774_;
  wire _0775_;
  wire _0776_;
  wire _0777_;
  wire _0778_;
  wire _0779_;
  wire _0780_;
  wire _0781_;
  wire _0782_;
  wire _0783_;
  wire _0784_;
  wire _0785_;
  wire _0786_;
  wire _0787_;
  wire _0788_;
  wire _0789_;
  wire _0790_;
  wire _0791_;
  wire _0792_;
  wire _0793_;
  wire _0794_;
  wire _0795_;
  wire _0796_;
  wire _0797_;
  wire _0798_;
  wire _0799_;
  wire _0800_;
  wire _0801_;
  wire _0802_;
  wire _0803_;
  wire _0804_;
  wire _0805_;
  wire _0806_;
  wire _0807_;
  wire _0808_;
  wire _0809_;
  wire _0810_;
  wire _0811_;
  wire _0812_;
  wire _0813_;
  wire _0814_;
  wire _0815_;
  wire _0816_;
  wire _0817_;
  wire _0818_;
  wire _0819_;
  wire _0820_;
  wire _0821_;
  wire _0822_;
  wire _0823_;
  wire _0824_;
  wire _0825_;
  wire _0826_;
  wire _0827_;
  wire _0828_;
  wire _0829_;
  wire _0830_;
  wire _0831_;
  wire _0832_;
  wire _0833_;
  (* src = "memoriaSynth.v:4" *)
  input clk;
  (* src = "memoriaSynth.v:2" *)
  input [11:0] data;
  (* src = "memoriaSynth.v:9" *)
  wire [31:0] i;
  wire [11:0] \mem[0] ;
  wire [11:0] \mem[1] ;
  wire [11:0] \mem[2] ;
  wire [11:0] \mem[3] ;
  wire [11:0] \mem[4] ;
  wire [11:0] \mem[5] ;
  wire [11:0] \mem[6] ;
  wire [11:0] \mem[7] ;
  (* src = "memoriaSynth.v:5" *)
  output [11:0] q;
  (* src = "memoriaSynth.v:3" *)
  input [2:0] rd_ptr;
  (* src = "memoriaSynth.v:4" *)
  input readSynth;
  (* src = "memoriaSynth.v:4" *)
  input reset;
  (* src = "memoriaSynth.v:3" *)
  input [2:0] wr_ptr;
  (* src = "memoriaSynth.v:4" *)
  input writeSynth;
  NOT _0834_ (
    .A(\mem[6] [0]),
    .Y(_0149_)
  );
  NOT _0835_ (
    .A(\mem[7] [0]),
    .Y(_0150_)
  );
  NOT _0836_ (
    .A(\mem[6] [1]),
    .Y(_0151_)
  );
  NOT _0837_ (
    .A(\mem[7] [1]),
    .Y(_0152_)
  );
  NOT _0838_ (
    .A(\mem[6] [2]),
    .Y(_0153_)
  );
  NOT _0839_ (
    .A(\mem[7] [2]),
    .Y(_0154_)
  );
  NOT _0840_ (
    .A(\mem[6] [3]),
    .Y(_0155_)
  );
  NOT _0841_ (
    .A(\mem[7] [3]),
    .Y(_0156_)
  );
  NOT _0842_ (
    .A(\mem[6] [4]),
    .Y(_0157_)
  );
  NOT _0843_ (
    .A(\mem[7] [4]),
    .Y(_0158_)
  );
  NOT _0844_ (
    .A(\mem[6] [5]),
    .Y(_0159_)
  );
  NOT _0845_ (
    .A(\mem[7] [5]),
    .Y(_0160_)
  );
  NOT _0846_ (
    .A(\mem[6] [6]),
    .Y(_0161_)
  );
  NOT _0847_ (
    .A(\mem[7] [6]),
    .Y(_0162_)
  );
  NOT _0848_ (
    .A(\mem[6] [7]),
    .Y(_0163_)
  );
  NOT _0849_ (
    .A(\mem[7] [7]),
    .Y(_0164_)
  );
  NOT _0850_ (
    .A(\mem[6] [8]),
    .Y(_0165_)
  );
  NOT _0851_ (
    .A(\mem[7] [8]),
    .Y(_0166_)
  );
  NOT _0852_ (
    .A(\mem[6] [9]),
    .Y(_0167_)
  );
  NOT _0853_ (
    .A(\mem[7] [9]),
    .Y(_0168_)
  );
  NOT _0854_ (
    .A(\mem[6] [10]),
    .Y(_0169_)
  );
  NOT _0855_ (
    .A(\mem[7] [10]),
    .Y(_0170_)
  );
  NOT _0856_ (
    .A(\mem[6] [11]),
    .Y(_0171_)
  );
  NOT _0857_ (
    .A(\mem[7] [11]),
    .Y(_0172_)
  );
  NOT _0858_ (
    .A(\mem[4] [0]),
    .Y(_0173_)
  );
  NOT _0859_ (
    .A(\mem[5] [0]),
    .Y(_0174_)
  );
  NOT _0860_ (
    .A(\mem[4] [1]),
    .Y(_0175_)
  );
  NOT _0861_ (
    .A(\mem[5] [1]),
    .Y(_0176_)
  );
  NOT _0862_ (
    .A(\mem[4] [2]),
    .Y(_0177_)
  );
  NOT _0863_ (
    .A(\mem[5] [2]),
    .Y(_0178_)
  );
  NOT _0864_ (
    .A(\mem[4] [3]),
    .Y(_0179_)
  );
  NOT _0865_ (
    .A(\mem[5] [3]),
    .Y(_0180_)
  );
  NOT _0866_ (
    .A(\mem[4] [4]),
    .Y(_0181_)
  );
  NOT _0867_ (
    .A(\mem[5] [4]),
    .Y(_0182_)
  );
  NOT _0868_ (
    .A(\mem[4] [5]),
    .Y(_0183_)
  );
  NOT _0869_ (
    .A(\mem[5] [5]),
    .Y(_0184_)
  );
  NOT _0870_ (
    .A(\mem[4] [6]),
    .Y(_0185_)
  );
  NOT _0871_ (
    .A(\mem[5] [6]),
    .Y(_0186_)
  );
  NOT _0872_ (
    .A(\mem[4] [7]),
    .Y(_0187_)
  );
  NOT _0873_ (
    .A(\mem[5] [7]),
    .Y(_0188_)
  );
  NOT _0874_ (
    .A(\mem[4] [8]),
    .Y(_0189_)
  );
  NOT _0875_ (
    .A(\mem[5] [8]),
    .Y(_0190_)
  );
  NOT _0876_ (
    .A(\mem[4] [9]),
    .Y(_0191_)
  );
  NOT _0877_ (
    .A(\mem[5] [9]),
    .Y(_0192_)
  );
  NOT _0878_ (
    .A(\mem[4] [10]),
    .Y(_0193_)
  );
  NOT _0879_ (
    .A(\mem[5] [10]),
    .Y(_0194_)
  );
  NOT _0880_ (
    .A(\mem[4] [11]),
    .Y(_0195_)
  );
  NOT _0881_ (
    .A(\mem[5] [11]),
    .Y(_0196_)
  );
  NOT _0882_ (
    .A(rd_ptr[1]),
    .Y(_0197_)
  );
  NOT _0883_ (
    .A(data[0]),
    .Y(_0198_)
  );
  NOT _0884_ (
    .A(data[1]),
    .Y(_0199_)
  );
  NOT _0885_ (
    .A(data[2]),
    .Y(_0200_)
  );
  NOT _0886_ (
    .A(data[3]),
    .Y(_0201_)
  );
  NOT _0887_ (
    .A(data[4]),
    .Y(_0202_)
  );
  NOT _0888_ (
    .A(data[5]),
    .Y(_0203_)
  );
  NOT _0889_ (
    .A(data[6]),
    .Y(_0204_)
  );
  NOT _0890_ (
    .A(data[7]),
    .Y(_0205_)
  );
  NOT _0891_ (
    .A(data[8]),
    .Y(_0206_)
  );
  NOT _0892_ (
    .A(data[9]),
    .Y(_0207_)
  );
  NOT _0893_ (
    .A(data[10]),
    .Y(_0208_)
  );
  NOT _0894_ (
    .A(data[11]),
    .Y(_0209_)
  );
  NAND _0895_ (
    .A(writeSynth),
    .B(wr_ptr[2]),
    .Y(_0210_)
  );
  NOT _0896_ (
    .A(_0210_),
    .Y(_0211_)
  );
  NAND _0897_ (
    .A(writeSynth),
    .B(wr_ptr[1]),
    .Y(_0212_)
  );
  NAND _0898_ (
    .A(reset),
    .B(_0212_),
    .Y(_0213_)
  );
  NOT _0899_ (
    .A(_0213_),
    .Y(_0214_)
  );
  NAND _0900_ (
    .A(reset),
    .B(_0210_),
    .Y(_0215_)
  );
  NOR _0901_ (
    .A(_0211_),
    .B(_0213_),
    .Y(_0216_)
  );
  NAND _0902_ (
    .A(_0210_),
    .B(_0214_),
    .Y(_0217_)
  );
  NAND _0903_ (
    .A(reset),
    .B(writeSynth),
    .Y(_0218_)
  );
  NOR _0904_ (
    .A(wr_ptr[0]),
    .B(_0218_),
    .Y(_0219_)
  );
  NAND _0905_ (
    .A(_0216_),
    .B(_0219_),
    .Y(_0220_)
  );
  NAND _0906_ (
    .A(reset),
    .B(\mem[0] [0]),
    .Y(_0221_)
  );
  NAND _0907_ (
    .A(_0220_),
    .B(_0221_),
    .Y(_0222_)
  );
  NOT _0908_ (
    .A(_0222_),
    .Y(_0223_)
  );
  NOR _0909_ (
    .A(data[0]),
    .B(_0220_),
    .Y(_0224_)
  );
  NOR _0910_ (
    .A(_0223_),
    .B(_0224_),
    .Y(_0000_)
  );
  NAND _0911_ (
    .A(reset),
    .B(\mem[0] [1]),
    .Y(_0225_)
  );
  NAND _0912_ (
    .A(_0220_),
    .B(_0225_),
    .Y(_0226_)
  );
  NOT _0913_ (
    .A(_0226_),
    .Y(_0227_)
  );
  NOR _0914_ (
    .A(data[1]),
    .B(_0220_),
    .Y(_0228_)
  );
  NOR _0915_ (
    .A(_0227_),
    .B(_0228_),
    .Y(_0003_)
  );
  NAND _0916_ (
    .A(reset),
    .B(\mem[0] [2]),
    .Y(_0229_)
  );
  NAND _0917_ (
    .A(_0220_),
    .B(_0229_),
    .Y(_0230_)
  );
  NOT _0918_ (
    .A(_0230_),
    .Y(_0231_)
  );
  NOR _0919_ (
    .A(data[2]),
    .B(_0220_),
    .Y(_0232_)
  );
  NOR _0920_ (
    .A(_0231_),
    .B(_0232_),
    .Y(_0004_)
  );
  NAND _0921_ (
    .A(reset),
    .B(\mem[0] [3]),
    .Y(_0233_)
  );
  NAND _0922_ (
    .A(_0220_),
    .B(_0233_),
    .Y(_0234_)
  );
  NOT _0923_ (
    .A(_0234_),
    .Y(_0235_)
  );
  NOR _0924_ (
    .A(data[3]),
    .B(_0220_),
    .Y(_0236_)
  );
  NOR _0925_ (
    .A(_0235_),
    .B(_0236_),
    .Y(_0005_)
  );
  NAND _0926_ (
    .A(reset),
    .B(\mem[0] [4]),
    .Y(_0237_)
  );
  NAND _0927_ (
    .A(_0220_),
    .B(_0237_),
    .Y(_0238_)
  );
  NOT _0928_ (
    .A(_0238_),
    .Y(_0239_)
  );
  NOR _0929_ (
    .A(data[4]),
    .B(_0220_),
    .Y(_0240_)
  );
  NOR _0930_ (
    .A(_0239_),
    .B(_0240_),
    .Y(_0006_)
  );
  NAND _0931_ (
    .A(reset),
    .B(\mem[0] [5]),
    .Y(_0241_)
  );
  NAND _0932_ (
    .A(_0220_),
    .B(_0241_),
    .Y(_0242_)
  );
  NOT _0933_ (
    .A(_0242_),
    .Y(_0243_)
  );
  NOR _0934_ (
    .A(data[5]),
    .B(_0220_),
    .Y(_0244_)
  );
  NOR _0935_ (
    .A(_0243_),
    .B(_0244_),
    .Y(_0007_)
  );
  NAND _0936_ (
    .A(reset),
    .B(\mem[0] [6]),
    .Y(_0245_)
  );
  NAND _0937_ (
    .A(_0220_),
    .B(_0245_),
    .Y(_0246_)
  );
  NOT _0938_ (
    .A(_0246_),
    .Y(_0247_)
  );
  NOR _0939_ (
    .A(data[6]),
    .B(_0220_),
    .Y(_0248_)
  );
  NOR _0940_ (
    .A(_0247_),
    .B(_0248_),
    .Y(_0008_)
  );
  NAND _0941_ (
    .A(reset),
    .B(\mem[0] [7]),
    .Y(_0249_)
  );
  NAND _0942_ (
    .A(_0220_),
    .B(_0249_),
    .Y(_0250_)
  );
  NOT _0943_ (
    .A(_0250_),
    .Y(_0251_)
  );
  NOR _0944_ (
    .A(data[7]),
    .B(_0220_),
    .Y(_0252_)
  );
  NOR _0945_ (
    .A(_0251_),
    .B(_0252_),
    .Y(_0009_)
  );
  NAND _0946_ (
    .A(reset),
    .B(\mem[0] [8]),
    .Y(_0253_)
  );
  NAND _0947_ (
    .A(_0220_),
    .B(_0253_),
    .Y(_0254_)
  );
  NOT _0948_ (
    .A(_0254_),
    .Y(_0255_)
  );
  NOR _0949_ (
    .A(data[8]),
    .B(_0220_),
    .Y(_0256_)
  );
  NOR _0950_ (
    .A(_0255_),
    .B(_0256_),
    .Y(_0010_)
  );
  NAND _0951_ (
    .A(reset),
    .B(\mem[0] [9]),
    .Y(_0257_)
  );
  NAND _0952_ (
    .A(_0220_),
    .B(_0257_),
    .Y(_0258_)
  );
  NOT _0953_ (
    .A(_0258_),
    .Y(_0259_)
  );
  NOR _0954_ (
    .A(data[9]),
    .B(_0220_),
    .Y(_0260_)
  );
  NOR _0955_ (
    .A(_0259_),
    .B(_0260_),
    .Y(_0011_)
  );
  NAND _0956_ (
    .A(reset),
    .B(\mem[0] [10]),
    .Y(_0261_)
  );
  NAND _0957_ (
    .A(_0220_),
    .B(_0261_),
    .Y(_0262_)
  );
  NOT _0958_ (
    .A(_0262_),
    .Y(_0263_)
  );
  NOR _0959_ (
    .A(data[10]),
    .B(_0220_),
    .Y(_0264_)
  );
  NOR _0960_ (
    .A(_0263_),
    .B(_0264_),
    .Y(_0001_)
  );
  NAND _0961_ (
    .A(reset),
    .B(\mem[0] [11]),
    .Y(_0265_)
  );
  NAND _0962_ (
    .A(_0220_),
    .B(_0265_),
    .Y(_0266_)
  );
  NOT _0963_ (
    .A(_0266_),
    .Y(_0267_)
  );
  NOR _0964_ (
    .A(data[11]),
    .B(_0220_),
    .Y(_0268_)
  );
  NOR _0965_ (
    .A(_0267_),
    .B(_0268_),
    .Y(_0002_)
  );
  NAND _0966_ (
    .A(reset),
    .B(readSynth),
    .Y(_0269_)
  );
  NAND _0967_ (
    .A(_0150_),
    .B(rd_ptr[2]),
    .Y(_0270_)
  );
  NOR _0968_ (
    .A(\mem[3] [0]),
    .B(rd_ptr[2]),
    .Y(_0271_)
  );
  NAND _0969_ (
    .A(rd_ptr[0]),
    .B(_0270_),
    .Y(_0272_)
  );
  NOR _0970_ (
    .A(_0271_),
    .B(_0272_),
    .Y(_0273_)
  );
  NOR _0971_ (
    .A(\mem[2] [0]),
    .B(rd_ptr[2]),
    .Y(_0274_)
  );
  NOT _0972_ (
    .A(_0274_),
    .Y(_0275_)
  );
  NAND _0973_ (
    .A(_0149_),
    .B(rd_ptr[2]),
    .Y(_0276_)
  );
  NAND _0974_ (
    .A(_0275_),
    .B(_0276_),
    .Y(_0277_)
  );
  NOR _0975_ (
    .A(rd_ptr[0]),
    .B(_0277_),
    .Y(_0278_)
  );
  NOR _0976_ (
    .A(_0273_),
    .B(_0278_),
    .Y(_0279_)
  );
  NOR _0977_ (
    .A(_0197_),
    .B(_0279_),
    .Y(_0280_)
  );
  NAND _0978_ (
    .A(_0174_),
    .B(rd_ptr[2]),
    .Y(_0281_)
  );
  NOR _0979_ (
    .A(\mem[1] [0]),
    .B(rd_ptr[2]),
    .Y(_0282_)
  );
  NAND _0980_ (
    .A(rd_ptr[0]),
    .B(_0281_),
    .Y(_0283_)
  );
  NOR _0981_ (
    .A(_0282_),
    .B(_0283_),
    .Y(_0284_)
  );
  NOR _0982_ (
    .A(\mem[0] [0]),
    .B(rd_ptr[2]),
    .Y(_0285_)
  );
  NOT _0983_ (
    .A(_0285_),
    .Y(_0286_)
  );
  NAND _0984_ (
    .A(_0173_),
    .B(rd_ptr[2]),
    .Y(_0287_)
  );
  NAND _0985_ (
    .A(_0286_),
    .B(_0287_),
    .Y(_0288_)
  );
  NOR _0986_ (
    .A(rd_ptr[0]),
    .B(_0288_),
    .Y(_0289_)
  );
  NOR _0987_ (
    .A(_0284_),
    .B(_0289_),
    .Y(_0290_)
  );
  NOR _0988_ (
    .A(rd_ptr[1]),
    .B(_0290_),
    .Y(_0291_)
  );
  NOR _0989_ (
    .A(_0280_),
    .B(_0291_),
    .Y(_0292_)
  );
  NOR _0990_ (
    .A(_0269_),
    .B(_0292_),
    .Y(q[0])
  );
  NAND _0991_ (
    .A(_0152_),
    .B(rd_ptr[2]),
    .Y(_0293_)
  );
  NOR _0992_ (
    .A(\mem[3] [1]),
    .B(rd_ptr[2]),
    .Y(_0294_)
  );
  NAND _0993_ (
    .A(rd_ptr[0]),
    .B(_0293_),
    .Y(_0295_)
  );
  NOR _0994_ (
    .A(_0294_),
    .B(_0295_),
    .Y(_0296_)
  );
  NOR _0995_ (
    .A(\mem[2] [1]),
    .B(rd_ptr[2]),
    .Y(_0297_)
  );
  NOT _0996_ (
    .A(_0297_),
    .Y(_0298_)
  );
  NAND _0997_ (
    .A(_0151_),
    .B(rd_ptr[2]),
    .Y(_0299_)
  );
  NAND _0998_ (
    .A(_0298_),
    .B(_0299_),
    .Y(_0300_)
  );
  NOR _0999_ (
    .A(rd_ptr[0]),
    .B(_0300_),
    .Y(_0301_)
  );
  NOR _1000_ (
    .A(_0296_),
    .B(_0301_),
    .Y(_0302_)
  );
  NOR _1001_ (
    .A(_0197_),
    .B(_0302_),
    .Y(_0303_)
  );
  NAND _1002_ (
    .A(_0176_),
    .B(rd_ptr[2]),
    .Y(_0304_)
  );
  NOR _1003_ (
    .A(\mem[1] [1]),
    .B(rd_ptr[2]),
    .Y(_0305_)
  );
  NAND _1004_ (
    .A(rd_ptr[0]),
    .B(_0304_),
    .Y(_0306_)
  );
  NOR _1005_ (
    .A(_0305_),
    .B(_0306_),
    .Y(_0307_)
  );
  NOR _1006_ (
    .A(\mem[0] [1]),
    .B(rd_ptr[2]),
    .Y(_0308_)
  );
  NOT _1007_ (
    .A(_0308_),
    .Y(_0309_)
  );
  NAND _1008_ (
    .A(_0175_),
    .B(rd_ptr[2]),
    .Y(_0310_)
  );
  NAND _1009_ (
    .A(_0309_),
    .B(_0310_),
    .Y(_0311_)
  );
  NOR _1010_ (
    .A(rd_ptr[0]),
    .B(_0311_),
    .Y(_0312_)
  );
  NOR _1011_ (
    .A(_0307_),
    .B(_0312_),
    .Y(_0313_)
  );
  NOR _1012_ (
    .A(rd_ptr[1]),
    .B(_0313_),
    .Y(_0314_)
  );
  NOR _1013_ (
    .A(_0303_),
    .B(_0314_),
    .Y(_0315_)
  );
  NOR _1014_ (
    .A(_0269_),
    .B(_0315_),
    .Y(q[1])
  );
  NAND _1015_ (
    .A(_0154_),
    .B(rd_ptr[2]),
    .Y(_0316_)
  );
  NOR _1016_ (
    .A(\mem[3] [2]),
    .B(rd_ptr[2]),
    .Y(_0317_)
  );
  NAND _1017_ (
    .A(rd_ptr[0]),
    .B(_0316_),
    .Y(_0318_)
  );
  NOR _1018_ (
    .A(_0317_),
    .B(_0318_),
    .Y(_0319_)
  );
  NOR _1019_ (
    .A(\mem[2] [2]),
    .B(rd_ptr[2]),
    .Y(_0320_)
  );
  NOT _1020_ (
    .A(_0320_),
    .Y(_0321_)
  );
  NAND _1021_ (
    .A(_0153_),
    .B(rd_ptr[2]),
    .Y(_0322_)
  );
  NAND _1022_ (
    .A(_0321_),
    .B(_0322_),
    .Y(_0323_)
  );
  NOR _1023_ (
    .A(rd_ptr[0]),
    .B(_0323_),
    .Y(_0324_)
  );
  NOR _1024_ (
    .A(_0319_),
    .B(_0324_),
    .Y(_0325_)
  );
  NOR _1025_ (
    .A(_0197_),
    .B(_0325_),
    .Y(_0326_)
  );
  NAND _1026_ (
    .A(_0178_),
    .B(rd_ptr[2]),
    .Y(_0327_)
  );
  NOR _1027_ (
    .A(\mem[1] [2]),
    .B(rd_ptr[2]),
    .Y(_0328_)
  );
  NAND _1028_ (
    .A(rd_ptr[0]),
    .B(_0327_),
    .Y(_0329_)
  );
  NOR _1029_ (
    .A(_0328_),
    .B(_0329_),
    .Y(_0330_)
  );
  NOR _1030_ (
    .A(\mem[0] [2]),
    .B(rd_ptr[2]),
    .Y(_0331_)
  );
  NOT _1031_ (
    .A(_0331_),
    .Y(_0332_)
  );
  NAND _1032_ (
    .A(_0177_),
    .B(rd_ptr[2]),
    .Y(_0333_)
  );
  NAND _1033_ (
    .A(_0332_),
    .B(_0333_),
    .Y(_0334_)
  );
  NOR _1034_ (
    .A(rd_ptr[0]),
    .B(_0334_),
    .Y(_0335_)
  );
  NOR _1035_ (
    .A(_0330_),
    .B(_0335_),
    .Y(_0336_)
  );
  NOR _1036_ (
    .A(rd_ptr[1]),
    .B(_0336_),
    .Y(_0337_)
  );
  NOR _1037_ (
    .A(_0326_),
    .B(_0337_),
    .Y(_0338_)
  );
  NOR _1038_ (
    .A(_0269_),
    .B(_0338_),
    .Y(q[2])
  );
  NAND _1039_ (
    .A(_0156_),
    .B(rd_ptr[2]),
    .Y(_0339_)
  );
  NOR _1040_ (
    .A(\mem[3] [3]),
    .B(rd_ptr[2]),
    .Y(_0340_)
  );
  NAND _1041_ (
    .A(rd_ptr[0]),
    .B(_0339_),
    .Y(_0341_)
  );
  NOR _1042_ (
    .A(_0340_),
    .B(_0341_),
    .Y(_0342_)
  );
  NOR _1043_ (
    .A(\mem[2] [3]),
    .B(rd_ptr[2]),
    .Y(_0343_)
  );
  NOT _1044_ (
    .A(_0343_),
    .Y(_0344_)
  );
  NAND _1045_ (
    .A(_0155_),
    .B(rd_ptr[2]),
    .Y(_0345_)
  );
  NAND _1046_ (
    .A(_0344_),
    .B(_0345_),
    .Y(_0346_)
  );
  NOR _1047_ (
    .A(rd_ptr[0]),
    .B(_0346_),
    .Y(_0347_)
  );
  NOR _1048_ (
    .A(_0342_),
    .B(_0347_),
    .Y(_0348_)
  );
  NOR _1049_ (
    .A(_0197_),
    .B(_0348_),
    .Y(_0349_)
  );
  NAND _1050_ (
    .A(_0180_),
    .B(rd_ptr[2]),
    .Y(_0350_)
  );
  NOR _1051_ (
    .A(\mem[1] [3]),
    .B(rd_ptr[2]),
    .Y(_0351_)
  );
  NAND _1052_ (
    .A(rd_ptr[0]),
    .B(_0350_),
    .Y(_0352_)
  );
  NOR _1053_ (
    .A(_0351_),
    .B(_0352_),
    .Y(_0353_)
  );
  NOR _1054_ (
    .A(\mem[0] [3]),
    .B(rd_ptr[2]),
    .Y(_0354_)
  );
  NOT _1055_ (
    .A(_0354_),
    .Y(_0355_)
  );
  NAND _1056_ (
    .A(_0179_),
    .B(rd_ptr[2]),
    .Y(_0356_)
  );
  NAND _1057_ (
    .A(_0355_),
    .B(_0356_),
    .Y(_0357_)
  );
  NOR _1058_ (
    .A(rd_ptr[0]),
    .B(_0357_),
    .Y(_0358_)
  );
  NOR _1059_ (
    .A(_0353_),
    .B(_0358_),
    .Y(_0359_)
  );
  NOR _1060_ (
    .A(rd_ptr[1]),
    .B(_0359_),
    .Y(_0360_)
  );
  NOR _1061_ (
    .A(_0349_),
    .B(_0360_),
    .Y(_0361_)
  );
  NOR _1062_ (
    .A(_0269_),
    .B(_0361_),
    .Y(q[3])
  );
  NAND _1063_ (
    .A(_0158_),
    .B(rd_ptr[2]),
    .Y(_0362_)
  );
  NOR _1064_ (
    .A(\mem[3] [4]),
    .B(rd_ptr[2]),
    .Y(_0363_)
  );
  NAND _1065_ (
    .A(rd_ptr[0]),
    .B(_0362_),
    .Y(_0364_)
  );
  NOR _1066_ (
    .A(_0363_),
    .B(_0364_),
    .Y(_0365_)
  );
  NOR _1067_ (
    .A(\mem[2] [4]),
    .B(rd_ptr[2]),
    .Y(_0366_)
  );
  NOT _1068_ (
    .A(_0366_),
    .Y(_0367_)
  );
  NAND _1069_ (
    .A(_0157_),
    .B(rd_ptr[2]),
    .Y(_0368_)
  );
  NAND _1070_ (
    .A(_0367_),
    .B(_0368_),
    .Y(_0369_)
  );
  NOR _1071_ (
    .A(rd_ptr[0]),
    .B(_0369_),
    .Y(_0370_)
  );
  NOR _1072_ (
    .A(_0365_),
    .B(_0370_),
    .Y(_0371_)
  );
  NOR _1073_ (
    .A(_0197_),
    .B(_0371_),
    .Y(_0372_)
  );
  NAND _1074_ (
    .A(_0182_),
    .B(rd_ptr[2]),
    .Y(_0373_)
  );
  NOR _1075_ (
    .A(\mem[1] [4]),
    .B(rd_ptr[2]),
    .Y(_0374_)
  );
  NAND _1076_ (
    .A(rd_ptr[0]),
    .B(_0373_),
    .Y(_0375_)
  );
  NOR _1077_ (
    .A(_0374_),
    .B(_0375_),
    .Y(_0376_)
  );
  NOR _1078_ (
    .A(\mem[0] [4]),
    .B(rd_ptr[2]),
    .Y(_0377_)
  );
  NOT _1079_ (
    .A(_0377_),
    .Y(_0378_)
  );
  NAND _1080_ (
    .A(_0181_),
    .B(rd_ptr[2]),
    .Y(_0379_)
  );
  NAND _1081_ (
    .A(_0378_),
    .B(_0379_),
    .Y(_0380_)
  );
  NOR _1082_ (
    .A(rd_ptr[0]),
    .B(_0380_),
    .Y(_0381_)
  );
  NOR _1083_ (
    .A(_0376_),
    .B(_0381_),
    .Y(_0382_)
  );
  NOR _1084_ (
    .A(rd_ptr[1]),
    .B(_0382_),
    .Y(_0383_)
  );
  NOR _1085_ (
    .A(_0372_),
    .B(_0383_),
    .Y(_0384_)
  );
  NOR _1086_ (
    .A(_0269_),
    .B(_0384_),
    .Y(q[4])
  );
  NAND _1087_ (
    .A(_0160_),
    .B(rd_ptr[2]),
    .Y(_0385_)
  );
  NOR _1088_ (
    .A(\mem[3] [5]),
    .B(rd_ptr[2]),
    .Y(_0386_)
  );
  NAND _1089_ (
    .A(rd_ptr[0]),
    .B(_0385_),
    .Y(_0387_)
  );
  NOR _1090_ (
    .A(_0386_),
    .B(_0387_),
    .Y(_0388_)
  );
  NOR _1091_ (
    .A(\mem[2] [5]),
    .B(rd_ptr[2]),
    .Y(_0389_)
  );
  NOT _1092_ (
    .A(_0389_),
    .Y(_0390_)
  );
  NAND _1093_ (
    .A(_0159_),
    .B(rd_ptr[2]),
    .Y(_0391_)
  );
  NAND _1094_ (
    .A(_0390_),
    .B(_0391_),
    .Y(_0392_)
  );
  NOR _1095_ (
    .A(rd_ptr[0]),
    .B(_0392_),
    .Y(_0393_)
  );
  NOR _1096_ (
    .A(_0388_),
    .B(_0393_),
    .Y(_0394_)
  );
  NOR _1097_ (
    .A(_0197_),
    .B(_0394_),
    .Y(_0395_)
  );
  NAND _1098_ (
    .A(_0184_),
    .B(rd_ptr[2]),
    .Y(_0396_)
  );
  NOR _1099_ (
    .A(\mem[1] [5]),
    .B(rd_ptr[2]),
    .Y(_0397_)
  );
  NAND _1100_ (
    .A(rd_ptr[0]),
    .B(_0396_),
    .Y(_0398_)
  );
  NOR _1101_ (
    .A(_0397_),
    .B(_0398_),
    .Y(_0399_)
  );
  NOR _1102_ (
    .A(\mem[0] [5]),
    .B(rd_ptr[2]),
    .Y(_0400_)
  );
  NOT _1103_ (
    .A(_0400_),
    .Y(_0401_)
  );
  NAND _1104_ (
    .A(_0183_),
    .B(rd_ptr[2]),
    .Y(_0402_)
  );
  NAND _1105_ (
    .A(_0401_),
    .B(_0402_),
    .Y(_0403_)
  );
  NOR _1106_ (
    .A(rd_ptr[0]),
    .B(_0403_),
    .Y(_0404_)
  );
  NOR _1107_ (
    .A(_0399_),
    .B(_0404_),
    .Y(_0405_)
  );
  NOR _1108_ (
    .A(rd_ptr[1]),
    .B(_0405_),
    .Y(_0406_)
  );
  NOR _1109_ (
    .A(_0395_),
    .B(_0406_),
    .Y(_0407_)
  );
  NOR _1110_ (
    .A(_0269_),
    .B(_0407_),
    .Y(q[5])
  );
  NAND _1111_ (
    .A(_0162_),
    .B(rd_ptr[2]),
    .Y(_0408_)
  );
  NOR _1112_ (
    .A(\mem[3] [6]),
    .B(rd_ptr[2]),
    .Y(_0409_)
  );
  NAND _1113_ (
    .A(rd_ptr[0]),
    .B(_0408_),
    .Y(_0410_)
  );
  NOR _1114_ (
    .A(_0409_),
    .B(_0410_),
    .Y(_0411_)
  );
  NOR _1115_ (
    .A(\mem[2] [6]),
    .B(rd_ptr[2]),
    .Y(_0412_)
  );
  NOT _1116_ (
    .A(_0412_),
    .Y(_0413_)
  );
  NAND _1117_ (
    .A(_0161_),
    .B(rd_ptr[2]),
    .Y(_0414_)
  );
  NAND _1118_ (
    .A(_0413_),
    .B(_0414_),
    .Y(_0415_)
  );
  NOR _1119_ (
    .A(rd_ptr[0]),
    .B(_0415_),
    .Y(_0416_)
  );
  NOR _1120_ (
    .A(_0411_),
    .B(_0416_),
    .Y(_0417_)
  );
  NOR _1121_ (
    .A(_0197_),
    .B(_0417_),
    .Y(_0418_)
  );
  NAND _1122_ (
    .A(_0186_),
    .B(rd_ptr[2]),
    .Y(_0419_)
  );
  NOR _1123_ (
    .A(\mem[1] [6]),
    .B(rd_ptr[2]),
    .Y(_0420_)
  );
  NAND _1124_ (
    .A(rd_ptr[0]),
    .B(_0419_),
    .Y(_0421_)
  );
  NOR _1125_ (
    .A(_0420_),
    .B(_0421_),
    .Y(_0422_)
  );
  NOR _1126_ (
    .A(\mem[0] [6]),
    .B(rd_ptr[2]),
    .Y(_0423_)
  );
  NOT _1127_ (
    .A(_0423_),
    .Y(_0424_)
  );
  NAND _1128_ (
    .A(_0185_),
    .B(rd_ptr[2]),
    .Y(_0425_)
  );
  NAND _1129_ (
    .A(_0424_),
    .B(_0425_),
    .Y(_0426_)
  );
  NOR _1130_ (
    .A(rd_ptr[0]),
    .B(_0426_),
    .Y(_0427_)
  );
  NOR _1131_ (
    .A(_0422_),
    .B(_0427_),
    .Y(_0428_)
  );
  NOR _1132_ (
    .A(rd_ptr[1]),
    .B(_0428_),
    .Y(_0429_)
  );
  NOR _1133_ (
    .A(_0418_),
    .B(_0429_),
    .Y(_0430_)
  );
  NOR _1134_ (
    .A(_0269_),
    .B(_0430_),
    .Y(q[6])
  );
  NAND _1135_ (
    .A(_0164_),
    .B(rd_ptr[2]),
    .Y(_0431_)
  );
  NOR _1136_ (
    .A(\mem[3] [7]),
    .B(rd_ptr[2]),
    .Y(_0432_)
  );
  NAND _1137_ (
    .A(rd_ptr[0]),
    .B(_0431_),
    .Y(_0433_)
  );
  NOR _1138_ (
    .A(_0432_),
    .B(_0433_),
    .Y(_0434_)
  );
  NOR _1139_ (
    .A(\mem[2] [7]),
    .B(rd_ptr[2]),
    .Y(_0435_)
  );
  NOT _1140_ (
    .A(_0435_),
    .Y(_0436_)
  );
  NAND _1141_ (
    .A(_0163_),
    .B(rd_ptr[2]),
    .Y(_0437_)
  );
  NAND _1142_ (
    .A(_0436_),
    .B(_0437_),
    .Y(_0438_)
  );
  NOR _1143_ (
    .A(rd_ptr[0]),
    .B(_0438_),
    .Y(_0439_)
  );
  NOR _1144_ (
    .A(_0434_),
    .B(_0439_),
    .Y(_0440_)
  );
  NOR _1145_ (
    .A(_0197_),
    .B(_0440_),
    .Y(_0441_)
  );
  NAND _1146_ (
    .A(_0188_),
    .B(rd_ptr[2]),
    .Y(_0442_)
  );
  NOR _1147_ (
    .A(\mem[1] [7]),
    .B(rd_ptr[2]),
    .Y(_0443_)
  );
  NAND _1148_ (
    .A(rd_ptr[0]),
    .B(_0442_),
    .Y(_0444_)
  );
  NOR _1149_ (
    .A(_0443_),
    .B(_0444_),
    .Y(_0445_)
  );
  NOR _1150_ (
    .A(\mem[0] [7]),
    .B(rd_ptr[2]),
    .Y(_0446_)
  );
  NOT _1151_ (
    .A(_0446_),
    .Y(_0447_)
  );
  NAND _1152_ (
    .A(_0187_),
    .B(rd_ptr[2]),
    .Y(_0448_)
  );
  NAND _1153_ (
    .A(_0447_),
    .B(_0448_),
    .Y(_0449_)
  );
  NOR _1154_ (
    .A(rd_ptr[0]),
    .B(_0449_),
    .Y(_0450_)
  );
  NOR _1155_ (
    .A(_0445_),
    .B(_0450_),
    .Y(_0451_)
  );
  NOR _1156_ (
    .A(rd_ptr[1]),
    .B(_0451_),
    .Y(_0452_)
  );
  NOR _1157_ (
    .A(_0441_),
    .B(_0452_),
    .Y(_0453_)
  );
  NOR _1158_ (
    .A(_0269_),
    .B(_0453_),
    .Y(q[7])
  );
  NAND _1159_ (
    .A(_0166_),
    .B(rd_ptr[2]),
    .Y(_0454_)
  );
  NOR _1160_ (
    .A(\mem[3] [8]),
    .B(rd_ptr[2]),
    .Y(_0455_)
  );
  NAND _1161_ (
    .A(rd_ptr[0]),
    .B(_0454_),
    .Y(_0456_)
  );
  NOR _1162_ (
    .A(_0455_),
    .B(_0456_),
    .Y(_0457_)
  );
  NOR _1163_ (
    .A(\mem[2] [8]),
    .B(rd_ptr[2]),
    .Y(_0458_)
  );
  NOT _1164_ (
    .A(_0458_),
    .Y(_0459_)
  );
  NAND _1165_ (
    .A(_0165_),
    .B(rd_ptr[2]),
    .Y(_0460_)
  );
  NAND _1166_ (
    .A(_0459_),
    .B(_0460_),
    .Y(_0461_)
  );
  NOR _1167_ (
    .A(rd_ptr[0]),
    .B(_0461_),
    .Y(_0462_)
  );
  NOR _1168_ (
    .A(_0457_),
    .B(_0462_),
    .Y(_0463_)
  );
  NOR _1169_ (
    .A(_0197_),
    .B(_0463_),
    .Y(_0464_)
  );
  NAND _1170_ (
    .A(_0190_),
    .B(rd_ptr[2]),
    .Y(_0465_)
  );
  NOR _1171_ (
    .A(\mem[1] [8]),
    .B(rd_ptr[2]),
    .Y(_0466_)
  );
  NAND _1172_ (
    .A(rd_ptr[0]),
    .B(_0465_),
    .Y(_0467_)
  );
  NOR _1173_ (
    .A(_0466_),
    .B(_0467_),
    .Y(_0468_)
  );
  NOR _1174_ (
    .A(\mem[0] [8]),
    .B(rd_ptr[2]),
    .Y(_0469_)
  );
  NOT _1175_ (
    .A(_0469_),
    .Y(_0470_)
  );
  NAND _1176_ (
    .A(_0189_),
    .B(rd_ptr[2]),
    .Y(_0471_)
  );
  NAND _1177_ (
    .A(_0470_),
    .B(_0471_),
    .Y(_0472_)
  );
  NOR _1178_ (
    .A(rd_ptr[0]),
    .B(_0472_),
    .Y(_0473_)
  );
  NOR _1179_ (
    .A(_0468_),
    .B(_0473_),
    .Y(_0474_)
  );
  NOR _1180_ (
    .A(rd_ptr[1]),
    .B(_0474_),
    .Y(_0475_)
  );
  NOR _1181_ (
    .A(_0464_),
    .B(_0475_),
    .Y(_0476_)
  );
  NOR _1182_ (
    .A(_0269_),
    .B(_0476_),
    .Y(q[8])
  );
  NAND _1183_ (
    .A(_0168_),
    .B(rd_ptr[2]),
    .Y(_0477_)
  );
  NOR _1184_ (
    .A(\mem[3] [9]),
    .B(rd_ptr[2]),
    .Y(_0478_)
  );
  NAND _1185_ (
    .A(rd_ptr[0]),
    .B(_0477_),
    .Y(_0479_)
  );
  NOR _1186_ (
    .A(_0478_),
    .B(_0479_),
    .Y(_0480_)
  );
  NOR _1187_ (
    .A(\mem[2] [9]),
    .B(rd_ptr[2]),
    .Y(_0481_)
  );
  NOT _1188_ (
    .A(_0481_),
    .Y(_0482_)
  );
  NAND _1189_ (
    .A(_0167_),
    .B(rd_ptr[2]),
    .Y(_0483_)
  );
  NAND _1190_ (
    .A(_0482_),
    .B(_0483_),
    .Y(_0484_)
  );
  NOR _1191_ (
    .A(rd_ptr[0]),
    .B(_0484_),
    .Y(_0485_)
  );
  NOR _1192_ (
    .A(_0480_),
    .B(_0485_),
    .Y(_0486_)
  );
  NOR _1193_ (
    .A(_0197_),
    .B(_0486_),
    .Y(_0487_)
  );
  NAND _1194_ (
    .A(_0192_),
    .B(rd_ptr[2]),
    .Y(_0488_)
  );
  NOR _1195_ (
    .A(\mem[1] [9]),
    .B(rd_ptr[2]),
    .Y(_0489_)
  );
  NAND _1196_ (
    .A(rd_ptr[0]),
    .B(_0488_),
    .Y(_0490_)
  );
  NOR _1197_ (
    .A(_0489_),
    .B(_0490_),
    .Y(_0491_)
  );
  NOR _1198_ (
    .A(\mem[0] [9]),
    .B(rd_ptr[2]),
    .Y(_0492_)
  );
  NOT _1199_ (
    .A(_0492_),
    .Y(_0493_)
  );
  NAND _1200_ (
    .A(_0191_),
    .B(rd_ptr[2]),
    .Y(_0494_)
  );
  NAND _1201_ (
    .A(_0493_),
    .B(_0494_),
    .Y(_0495_)
  );
  NOR _1202_ (
    .A(rd_ptr[0]),
    .B(_0495_),
    .Y(_0496_)
  );
  NOR _1203_ (
    .A(_0491_),
    .B(_0496_),
    .Y(_0497_)
  );
  NOR _1204_ (
    .A(rd_ptr[1]),
    .B(_0497_),
    .Y(_0498_)
  );
  NOR _1205_ (
    .A(_0487_),
    .B(_0498_),
    .Y(_0499_)
  );
  NOR _1206_ (
    .A(_0269_),
    .B(_0499_),
    .Y(q[9])
  );
  NAND _1207_ (
    .A(_0170_),
    .B(rd_ptr[2]),
    .Y(_0500_)
  );
  NOR _1208_ (
    .A(\mem[3] [10]),
    .B(rd_ptr[2]),
    .Y(_0501_)
  );
  NAND _1209_ (
    .A(rd_ptr[0]),
    .B(_0500_),
    .Y(_0502_)
  );
  NOR _1210_ (
    .A(_0501_),
    .B(_0502_),
    .Y(_0503_)
  );
  NOR _1211_ (
    .A(\mem[2] [10]),
    .B(rd_ptr[2]),
    .Y(_0504_)
  );
  NOT _1212_ (
    .A(_0504_),
    .Y(_0505_)
  );
  NAND _1213_ (
    .A(_0169_),
    .B(rd_ptr[2]),
    .Y(_0506_)
  );
  NAND _1214_ (
    .A(_0505_),
    .B(_0506_),
    .Y(_0507_)
  );
  NOR _1215_ (
    .A(rd_ptr[0]),
    .B(_0507_),
    .Y(_0508_)
  );
  NOR _1216_ (
    .A(_0503_),
    .B(_0508_),
    .Y(_0509_)
  );
  NOR _1217_ (
    .A(_0197_),
    .B(_0509_),
    .Y(_0510_)
  );
  NAND _1218_ (
    .A(_0194_),
    .B(rd_ptr[2]),
    .Y(_0511_)
  );
  NOR _1219_ (
    .A(\mem[1] [10]),
    .B(rd_ptr[2]),
    .Y(_0512_)
  );
  NAND _1220_ (
    .A(rd_ptr[0]),
    .B(_0511_),
    .Y(_0513_)
  );
  NOR _1221_ (
    .A(_0512_),
    .B(_0513_),
    .Y(_0514_)
  );
  NOR _1222_ (
    .A(\mem[0] [10]),
    .B(rd_ptr[2]),
    .Y(_0515_)
  );
  NOT _1223_ (
    .A(_0515_),
    .Y(_0516_)
  );
  NAND _1224_ (
    .A(_0193_),
    .B(rd_ptr[2]),
    .Y(_0517_)
  );
  NAND _1225_ (
    .A(_0516_),
    .B(_0517_),
    .Y(_0518_)
  );
  NOR _1226_ (
    .A(rd_ptr[0]),
    .B(_0518_),
    .Y(_0519_)
  );
  NOR _1227_ (
    .A(_0514_),
    .B(_0519_),
    .Y(_0520_)
  );
  NOR _1228_ (
    .A(rd_ptr[1]),
    .B(_0520_),
    .Y(_0521_)
  );
  NOR _1229_ (
    .A(_0510_),
    .B(_0521_),
    .Y(_0522_)
  );
  NOR _1230_ (
    .A(_0269_),
    .B(_0522_),
    .Y(q[10])
  );
  NAND _1231_ (
    .A(_0172_),
    .B(rd_ptr[2]),
    .Y(_0523_)
  );
  NOR _1232_ (
    .A(\mem[3] [11]),
    .B(rd_ptr[2]),
    .Y(_0524_)
  );
  NAND _1233_ (
    .A(rd_ptr[0]),
    .B(_0523_),
    .Y(_0525_)
  );
  NOR _1234_ (
    .A(_0524_),
    .B(_0525_),
    .Y(_0526_)
  );
  NOR _1235_ (
    .A(\mem[2] [11]),
    .B(rd_ptr[2]),
    .Y(_0527_)
  );
  NOT _1236_ (
    .A(_0527_),
    .Y(_0528_)
  );
  NAND _1237_ (
    .A(_0171_),
    .B(rd_ptr[2]),
    .Y(_0529_)
  );
  NAND _1238_ (
    .A(_0528_),
    .B(_0529_),
    .Y(_0530_)
  );
  NOR _1239_ (
    .A(rd_ptr[0]),
    .B(_0530_),
    .Y(_0531_)
  );
  NOR _1240_ (
    .A(_0526_),
    .B(_0531_),
    .Y(_0532_)
  );
  NOR _1241_ (
    .A(_0197_),
    .B(_0532_),
    .Y(_0533_)
  );
  NAND _1242_ (
    .A(_0196_),
    .B(rd_ptr[2]),
    .Y(_0534_)
  );
  NOR _1243_ (
    .A(\mem[1] [11]),
    .B(rd_ptr[2]),
    .Y(_0535_)
  );
  NAND _1244_ (
    .A(rd_ptr[0]),
    .B(_0534_),
    .Y(_0536_)
  );
  NOR _1245_ (
    .A(_0535_),
    .B(_0536_),
    .Y(_0537_)
  );
  NOR _1246_ (
    .A(\mem[0] [11]),
    .B(rd_ptr[2]),
    .Y(_0538_)
  );
  NOT _1247_ (
    .A(_0538_),
    .Y(_0539_)
  );
  NAND _1248_ (
    .A(_0195_),
    .B(rd_ptr[2]),
    .Y(_0540_)
  );
  NAND _1249_ (
    .A(_0539_),
    .B(_0540_),
    .Y(_0541_)
  );
  NOR _1250_ (
    .A(rd_ptr[0]),
    .B(_0541_),
    .Y(_0542_)
  );
  NOR _1251_ (
    .A(_0537_),
    .B(_0542_),
    .Y(_0543_)
  );
  NOR _1252_ (
    .A(rd_ptr[1]),
    .B(_0543_),
    .Y(_0544_)
  );
  NOR _1253_ (
    .A(_0533_),
    .B(_0544_),
    .Y(_0545_)
  );
  NOR _1254_ (
    .A(_0269_),
    .B(_0545_),
    .Y(q[11])
  );
  NAND _1255_ (
    .A(writeSynth),
    .B(wr_ptr[0]),
    .Y(_0546_)
  );
  NOR _1256_ (
    .A(_0217_),
    .B(_0546_),
    .Y(_0547_)
  );
  NAND _1257_ (
    .A(\mem[1] [0]),
    .B(reset),
    .Y(_0548_)
  );
  NOR _1258_ (
    .A(_0198_),
    .B(_0218_),
    .Y(_0549_)
  );
  NAND _1259_ (
    .A(_0547_),
    .B(_0549_),
    .Y(_0550_)
  );
  NOR _1260_ (
    .A(_0547_),
    .B(_0548_),
    .Y(_0551_)
  );
  NOT _1261_ (
    .A(_0551_),
    .Y(_0552_)
  );
  NAND _1262_ (
    .A(_0550_),
    .B(_0552_),
    .Y(_0012_)
  );
  NAND _1263_ (
    .A(\mem[1] [1]),
    .B(reset),
    .Y(_0553_)
  );
  NOR _1264_ (
    .A(_0199_),
    .B(_0218_),
    .Y(_0554_)
  );
  NAND _1265_ (
    .A(_0547_),
    .B(_0554_),
    .Y(_0555_)
  );
  NOR _1266_ (
    .A(_0547_),
    .B(_0553_),
    .Y(_0556_)
  );
  NOT _1267_ (
    .A(_0556_),
    .Y(_0557_)
  );
  NAND _1268_ (
    .A(_0555_),
    .B(_0557_),
    .Y(_0015_)
  );
  NAND _1269_ (
    .A(\mem[1] [2]),
    .B(reset),
    .Y(_0558_)
  );
  NOR _1270_ (
    .A(_0200_),
    .B(_0218_),
    .Y(_0559_)
  );
  NAND _1271_ (
    .A(_0547_),
    .B(_0559_),
    .Y(_0560_)
  );
  NOR _1272_ (
    .A(_0547_),
    .B(_0558_),
    .Y(_0561_)
  );
  NOT _1273_ (
    .A(_0561_),
    .Y(_0562_)
  );
  NAND _1274_ (
    .A(_0560_),
    .B(_0562_),
    .Y(_0016_)
  );
  NAND _1275_ (
    .A(\mem[1] [3]),
    .B(reset),
    .Y(_0563_)
  );
  NOR _1276_ (
    .A(_0201_),
    .B(_0218_),
    .Y(_0564_)
  );
  NAND _1277_ (
    .A(_0547_),
    .B(_0564_),
    .Y(_0565_)
  );
  NOR _1278_ (
    .A(_0547_),
    .B(_0563_),
    .Y(_0566_)
  );
  NOT _1279_ (
    .A(_0566_),
    .Y(_0567_)
  );
  NAND _1280_ (
    .A(_0565_),
    .B(_0567_),
    .Y(_0017_)
  );
  NAND _1281_ (
    .A(\mem[1] [4]),
    .B(reset),
    .Y(_0568_)
  );
  NOR _1282_ (
    .A(_0202_),
    .B(_0218_),
    .Y(_0569_)
  );
  NAND _1283_ (
    .A(_0547_),
    .B(_0569_),
    .Y(_0570_)
  );
  NOR _1284_ (
    .A(_0547_),
    .B(_0568_),
    .Y(_0571_)
  );
  NOT _1285_ (
    .A(_0571_),
    .Y(_0572_)
  );
  NAND _1286_ (
    .A(_0570_),
    .B(_0572_),
    .Y(_0018_)
  );
  NAND _1287_ (
    .A(\mem[1] [5]),
    .B(reset),
    .Y(_0573_)
  );
  NOR _1288_ (
    .A(_0203_),
    .B(_0218_),
    .Y(_0574_)
  );
  NAND _1289_ (
    .A(_0547_),
    .B(_0574_),
    .Y(_0575_)
  );
  NOR _1290_ (
    .A(_0547_),
    .B(_0573_),
    .Y(_0576_)
  );
  NOT _1291_ (
    .A(_0576_),
    .Y(_0577_)
  );
  NAND _1292_ (
    .A(_0575_),
    .B(_0577_),
    .Y(_0019_)
  );
  NAND _1293_ (
    .A(\mem[1] [6]),
    .B(reset),
    .Y(_0578_)
  );
  NOR _1294_ (
    .A(_0204_),
    .B(_0218_),
    .Y(_0579_)
  );
  NAND _1295_ (
    .A(_0547_),
    .B(_0579_),
    .Y(_0580_)
  );
  NOR _1296_ (
    .A(_0547_),
    .B(_0578_),
    .Y(_0581_)
  );
  NOT _1297_ (
    .A(_0581_),
    .Y(_0582_)
  );
  NAND _1298_ (
    .A(_0580_),
    .B(_0582_),
    .Y(_0020_)
  );
  NAND _1299_ (
    .A(\mem[1] [7]),
    .B(reset),
    .Y(_0583_)
  );
  NOR _1300_ (
    .A(_0205_),
    .B(_0218_),
    .Y(_0584_)
  );
  NAND _1301_ (
    .A(_0547_),
    .B(_0584_),
    .Y(_0585_)
  );
  NOR _1302_ (
    .A(_0547_),
    .B(_0583_),
    .Y(_0586_)
  );
  NOT _1303_ (
    .A(_0586_),
    .Y(_0587_)
  );
  NAND _1304_ (
    .A(_0585_),
    .B(_0587_),
    .Y(_0021_)
  );
  NAND _1305_ (
    .A(\mem[1] [8]),
    .B(reset),
    .Y(_0588_)
  );
  NOR _1306_ (
    .A(_0206_),
    .B(_0218_),
    .Y(_0589_)
  );
  NAND _1307_ (
    .A(_0547_),
    .B(_0589_),
    .Y(_0590_)
  );
  NOR _1308_ (
    .A(_0547_),
    .B(_0588_),
    .Y(_0591_)
  );
  NOT _1309_ (
    .A(_0591_),
    .Y(_0592_)
  );
  NAND _1310_ (
    .A(_0590_),
    .B(_0592_),
    .Y(_0022_)
  );
  NAND _1311_ (
    .A(\mem[1] [9]),
    .B(reset),
    .Y(_0593_)
  );
  NOR _1312_ (
    .A(_0207_),
    .B(_0218_),
    .Y(_0594_)
  );
  NAND _1313_ (
    .A(_0547_),
    .B(_0594_),
    .Y(_0595_)
  );
  NOR _1314_ (
    .A(_0547_),
    .B(_0593_),
    .Y(_0596_)
  );
  NOT _1315_ (
    .A(_0596_),
    .Y(_0597_)
  );
  NAND _1316_ (
    .A(_0595_),
    .B(_0597_),
    .Y(_0023_)
  );
  NAND _1317_ (
    .A(\mem[1] [10]),
    .B(reset),
    .Y(_0598_)
  );
  NOR _1318_ (
    .A(_0208_),
    .B(_0218_),
    .Y(_0599_)
  );
  NAND _1319_ (
    .A(_0547_),
    .B(_0599_),
    .Y(_0600_)
  );
  NOR _1320_ (
    .A(_0547_),
    .B(_0598_),
    .Y(_0601_)
  );
  NOT _1321_ (
    .A(_0601_),
    .Y(_0602_)
  );
  NAND _1322_ (
    .A(_0600_),
    .B(_0602_),
    .Y(_0013_)
  );
  NAND _1323_ (
    .A(\mem[1] [11]),
    .B(reset),
    .Y(_0603_)
  );
  NOR _1324_ (
    .A(_0209_),
    .B(_0218_),
    .Y(_0604_)
  );
  NAND _1325_ (
    .A(_0547_),
    .B(_0604_),
    .Y(_0605_)
  );
  NOR _1326_ (
    .A(_0547_),
    .B(_0603_),
    .Y(_0606_)
  );
  NOT _1327_ (
    .A(_0606_),
    .Y(_0607_)
  );
  NAND _1328_ (
    .A(_0605_),
    .B(_0607_),
    .Y(_0014_)
  );
  NOR _1329_ (
    .A(_0212_),
    .B(_0215_),
    .Y(_0608_)
  );
  NOT _1330_ (
    .A(_0608_),
    .Y(_0609_)
  );
  NOR _1331_ (
    .A(wr_ptr[0]),
    .B(_0609_),
    .Y(_0610_)
  );
  NAND _1332_ (
    .A(\mem[2] [0]),
    .B(reset),
    .Y(_0611_)
  );
  NAND _1333_ (
    .A(_0549_),
    .B(_0610_),
    .Y(_0612_)
  );
  NOR _1334_ (
    .A(_0610_),
    .B(_0611_),
    .Y(_0613_)
  );
  NOT _1335_ (
    .A(_0613_),
    .Y(_0614_)
  );
  NAND _1336_ (
    .A(_0612_),
    .B(_0614_),
    .Y(_0024_)
  );
  NAND _1337_ (
    .A(\mem[2] [1]),
    .B(reset),
    .Y(_0615_)
  );
  NAND _1338_ (
    .A(_0554_),
    .B(_0610_),
    .Y(_0616_)
  );
  NOR _1339_ (
    .A(_0610_),
    .B(_0615_),
    .Y(_0617_)
  );
  NOT _1340_ (
    .A(_0617_),
    .Y(_0618_)
  );
  NAND _1341_ (
    .A(_0616_),
    .B(_0618_),
    .Y(_0027_)
  );
  NAND _1342_ (
    .A(\mem[2] [2]),
    .B(reset),
    .Y(_0619_)
  );
  NAND _1343_ (
    .A(_0559_),
    .B(_0610_),
    .Y(_0620_)
  );
  NOR _1344_ (
    .A(_0610_),
    .B(_0619_),
    .Y(_0621_)
  );
  NOT _1345_ (
    .A(_0621_),
    .Y(_0622_)
  );
  NAND _1346_ (
    .A(_0620_),
    .B(_0622_),
    .Y(_0028_)
  );
  NAND _1347_ (
    .A(\mem[2] [3]),
    .B(reset),
    .Y(_0623_)
  );
  NAND _1348_ (
    .A(_0564_),
    .B(_0610_),
    .Y(_0624_)
  );
  NOR _1349_ (
    .A(_0610_),
    .B(_0623_),
    .Y(_0625_)
  );
  NOT _1350_ (
    .A(_0625_),
    .Y(_0626_)
  );
  NAND _1351_ (
    .A(_0624_),
    .B(_0626_),
    .Y(_0029_)
  );
  NAND _1352_ (
    .A(\mem[2] [4]),
    .B(reset),
    .Y(_0627_)
  );
  NAND _1353_ (
    .A(_0569_),
    .B(_0610_),
    .Y(_0628_)
  );
  NOR _1354_ (
    .A(_0610_),
    .B(_0627_),
    .Y(_0629_)
  );
  NOT _1355_ (
    .A(_0629_),
    .Y(_0630_)
  );
  NAND _1356_ (
    .A(_0628_),
    .B(_0630_),
    .Y(_0030_)
  );
  NAND _1357_ (
    .A(\mem[2] [5]),
    .B(reset),
    .Y(_0631_)
  );
  NAND _1358_ (
    .A(_0574_),
    .B(_0610_),
    .Y(_0632_)
  );
  NOR _1359_ (
    .A(_0610_),
    .B(_0631_),
    .Y(_0633_)
  );
  NOT _1360_ (
    .A(_0633_),
    .Y(_0634_)
  );
  NAND _1361_ (
    .A(_0632_),
    .B(_0634_),
    .Y(_0031_)
  );
  NAND _1362_ (
    .A(\mem[2] [6]),
    .B(reset),
    .Y(_0635_)
  );
  NAND _1363_ (
    .A(_0579_),
    .B(_0610_),
    .Y(_0636_)
  );
  NOR _1364_ (
    .A(_0610_),
    .B(_0635_),
    .Y(_0637_)
  );
  NOT _1365_ (
    .A(_0637_),
    .Y(_0638_)
  );
  NAND _1366_ (
    .A(_0636_),
    .B(_0638_),
    .Y(_0032_)
  );
  NAND _1367_ (
    .A(\mem[2] [7]),
    .B(reset),
    .Y(_0639_)
  );
  NAND _1368_ (
    .A(_0584_),
    .B(_0610_),
    .Y(_0640_)
  );
  NOR _1369_ (
    .A(_0610_),
    .B(_0639_),
    .Y(_0641_)
  );
  NOT _1370_ (
    .A(_0641_),
    .Y(_0642_)
  );
  NAND _1371_ (
    .A(_0640_),
    .B(_0642_),
    .Y(_0033_)
  );
  NAND _1372_ (
    .A(\mem[2] [8]),
    .B(reset),
    .Y(_0643_)
  );
  NAND _1373_ (
    .A(_0589_),
    .B(_0610_),
    .Y(_0644_)
  );
  NOR _1374_ (
    .A(_0610_),
    .B(_0643_),
    .Y(_0645_)
  );
  NOT _1375_ (
    .A(_0645_),
    .Y(_0646_)
  );
  NAND _1376_ (
    .A(_0644_),
    .B(_0646_),
    .Y(_0034_)
  );
  NAND _1377_ (
    .A(\mem[2] [9]),
    .B(reset),
    .Y(_0647_)
  );
  NAND _1378_ (
    .A(_0594_),
    .B(_0610_),
    .Y(_0648_)
  );
  NOR _1379_ (
    .A(_0610_),
    .B(_0647_),
    .Y(_0649_)
  );
  NOT _1380_ (
    .A(_0649_),
    .Y(_0650_)
  );
  NAND _1381_ (
    .A(_0648_),
    .B(_0650_),
    .Y(_0035_)
  );
  NAND _1382_ (
    .A(\mem[2] [10]),
    .B(reset),
    .Y(_0651_)
  );
  NAND _1383_ (
    .A(_0599_),
    .B(_0610_),
    .Y(_0652_)
  );
  NOR _1384_ (
    .A(_0610_),
    .B(_0651_),
    .Y(_0653_)
  );
  NOT _1385_ (
    .A(_0653_),
    .Y(_0654_)
  );
  NAND _1386_ (
    .A(_0652_),
    .B(_0654_),
    .Y(_0025_)
  );
  NAND _1387_ (
    .A(\mem[2] [11]),
    .B(reset),
    .Y(_0655_)
  );
  NAND _1388_ (
    .A(_0604_),
    .B(_0610_),
    .Y(_0656_)
  );
  NOR _1389_ (
    .A(_0610_),
    .B(_0655_),
    .Y(_0657_)
  );
  NOT _1390_ (
    .A(_0657_),
    .Y(_0658_)
  );
  NAND _1391_ (
    .A(_0656_),
    .B(_0658_),
    .Y(_0026_)
  );
  NAND _1392_ (
    .A(wr_ptr[0]),
    .B(_0608_),
    .Y(_0659_)
  );
  NAND _1393_ (
    .A(reset),
    .B(\mem[3] [0]),
    .Y(_0660_)
  );
  NAND _1394_ (
    .A(_0659_),
    .B(_0660_),
    .Y(_0661_)
  );
  NOT _1395_ (
    .A(_0661_),
    .Y(_0662_)
  );
  NOR _1396_ (
    .A(_0549_),
    .B(_0659_),
    .Y(_0663_)
  );
  NOR _1397_ (
    .A(_0662_),
    .B(_0663_),
    .Y(_0036_)
  );
  NAND _1398_ (
    .A(reset),
    .B(\mem[3] [1]),
    .Y(_0664_)
  );
  NAND _1399_ (
    .A(_0659_),
    .B(_0664_),
    .Y(_0665_)
  );
  NOT _1400_ (
    .A(_0665_),
    .Y(_0666_)
  );
  NOR _1401_ (
    .A(_0554_),
    .B(_0659_),
    .Y(_0667_)
  );
  NOR _1402_ (
    .A(_0666_),
    .B(_0667_),
    .Y(_0039_)
  );
  NAND _1403_ (
    .A(reset),
    .B(\mem[3] [2]),
    .Y(_0668_)
  );
  NAND _1404_ (
    .A(_0659_),
    .B(_0668_),
    .Y(_0669_)
  );
  NOT _1405_ (
    .A(_0669_),
    .Y(_0670_)
  );
  NOR _1406_ (
    .A(_0559_),
    .B(_0659_),
    .Y(_0671_)
  );
  NOR _1407_ (
    .A(_0670_),
    .B(_0671_),
    .Y(_0040_)
  );
  NAND _1408_ (
    .A(reset),
    .B(\mem[3] [3]),
    .Y(_0672_)
  );
  NAND _1409_ (
    .A(_0659_),
    .B(_0672_),
    .Y(_0673_)
  );
  NOT _1410_ (
    .A(_0673_),
    .Y(_0674_)
  );
  NOR _1411_ (
    .A(_0564_),
    .B(_0659_),
    .Y(_0675_)
  );
  NOR _1412_ (
    .A(_0674_),
    .B(_0675_),
    .Y(_0041_)
  );
  NAND _1413_ (
    .A(reset),
    .B(\mem[3] [4]),
    .Y(_0676_)
  );
  NAND _1414_ (
    .A(_0659_),
    .B(_0676_),
    .Y(_0677_)
  );
  NOT _1415_ (
    .A(_0677_),
    .Y(_0678_)
  );
  NOR _1416_ (
    .A(_0569_),
    .B(_0659_),
    .Y(_0679_)
  );
  NOR _1417_ (
    .A(_0678_),
    .B(_0679_),
    .Y(_0042_)
  );
  NAND _1418_ (
    .A(reset),
    .B(\mem[3] [5]),
    .Y(_0680_)
  );
  NAND _1419_ (
    .A(_0659_),
    .B(_0680_),
    .Y(_0681_)
  );
  NOT _1420_ (
    .A(_0681_),
    .Y(_0682_)
  );
  NOR _1421_ (
    .A(_0574_),
    .B(_0659_),
    .Y(_0683_)
  );
  NOR _1422_ (
    .A(_0682_),
    .B(_0683_),
    .Y(_0043_)
  );
  NAND _1423_ (
    .A(reset),
    .B(\mem[3] [6]),
    .Y(_0684_)
  );
  NAND _1424_ (
    .A(_0659_),
    .B(_0684_),
    .Y(_0685_)
  );
  NOT _1425_ (
    .A(_0685_),
    .Y(_0686_)
  );
  NOR _1426_ (
    .A(_0579_),
    .B(_0659_),
    .Y(_0687_)
  );
  NOR _1427_ (
    .A(_0686_),
    .B(_0687_),
    .Y(_0044_)
  );
  NAND _1428_ (
    .A(reset),
    .B(\mem[3] [7]),
    .Y(_0688_)
  );
  NAND _1429_ (
    .A(_0659_),
    .B(_0688_),
    .Y(_0689_)
  );
  NOT _1430_ (
    .A(_0689_),
    .Y(_0690_)
  );
  NOR _1431_ (
    .A(_0584_),
    .B(_0659_),
    .Y(_0691_)
  );
  NOR _1432_ (
    .A(_0690_),
    .B(_0691_),
    .Y(_0045_)
  );
  NAND _1433_ (
    .A(reset),
    .B(\mem[3] [8]),
    .Y(_0692_)
  );
  NAND _1434_ (
    .A(_0659_),
    .B(_0692_),
    .Y(_0693_)
  );
  NOT _1435_ (
    .A(_0693_),
    .Y(_0694_)
  );
  NOR _1436_ (
    .A(_0589_),
    .B(_0659_),
    .Y(_0695_)
  );
  NOR _1437_ (
    .A(_0694_),
    .B(_0695_),
    .Y(_0046_)
  );
  NAND _1438_ (
    .A(reset),
    .B(\mem[3] [9]),
    .Y(_0696_)
  );
  NAND _1439_ (
    .A(_0659_),
    .B(_0696_),
    .Y(_0697_)
  );
  NOT _1440_ (
    .A(_0697_),
    .Y(_0698_)
  );
  NOR _1441_ (
    .A(_0594_),
    .B(_0659_),
    .Y(_0699_)
  );
  NOR _1442_ (
    .A(_0698_),
    .B(_0699_),
    .Y(_0047_)
  );
  NAND _1443_ (
    .A(reset),
    .B(\mem[3] [10]),
    .Y(_0700_)
  );
  NAND _1444_ (
    .A(_0659_),
    .B(_0700_),
    .Y(_0701_)
  );
  NOT _1445_ (
    .A(_0701_),
    .Y(_0702_)
  );
  NOR _1446_ (
    .A(_0599_),
    .B(_0659_),
    .Y(_0703_)
  );
  NOR _1447_ (
    .A(_0702_),
    .B(_0703_),
    .Y(_0037_)
  );
  NAND _1448_ (
    .A(reset),
    .B(\mem[3] [11]),
    .Y(_0704_)
  );
  NAND _1449_ (
    .A(_0659_),
    .B(_0704_),
    .Y(_0705_)
  );
  NOT _1450_ (
    .A(_0705_),
    .Y(_0706_)
  );
  NOR _1451_ (
    .A(_0604_),
    .B(_0659_),
    .Y(_0707_)
  );
  NOR _1452_ (
    .A(_0706_),
    .B(_0707_),
    .Y(_0038_)
  );
  NOR _1453_ (
    .A(_0210_),
    .B(_0213_),
    .Y(_0708_)
  );
  NOT _1454_ (
    .A(_0708_),
    .Y(_0709_)
  );
  NOR _1455_ (
    .A(wr_ptr[0]),
    .B(_0709_),
    .Y(_0710_)
  );
  NAND _1456_ (
    .A(reset),
    .B(\mem[4] [0]),
    .Y(_0711_)
  );
  NAND _1457_ (
    .A(_0549_),
    .B(_0710_),
    .Y(_0712_)
  );
  NOR _1458_ (
    .A(_0710_),
    .B(_0711_),
    .Y(_0713_)
  );
  NOT _1459_ (
    .A(_0713_),
    .Y(_0714_)
  );
  NAND _1460_ (
    .A(_0712_),
    .B(_0714_),
    .Y(_0048_)
  );
  NAND _1461_ (
    .A(reset),
    .B(\mem[4] [1]),
    .Y(_0715_)
  );
  NAND _1462_ (
    .A(_0554_),
    .B(_0710_),
    .Y(_0716_)
  );
  NOR _1463_ (
    .A(_0710_),
    .B(_0715_),
    .Y(_0717_)
  );
  NOT _1464_ (
    .A(_0717_),
    .Y(_0718_)
  );
  NAND _1465_ (
    .A(_0716_),
    .B(_0718_),
    .Y(_0051_)
  );
  NAND _1466_ (
    .A(reset),
    .B(\mem[4] [2]),
    .Y(_0719_)
  );
  NAND _1467_ (
    .A(_0559_),
    .B(_0710_),
    .Y(_0720_)
  );
  NOR _1468_ (
    .A(_0710_),
    .B(_0719_),
    .Y(_0721_)
  );
  NOT _1469_ (
    .A(_0721_),
    .Y(_0722_)
  );
  NAND _1470_ (
    .A(_0720_),
    .B(_0722_),
    .Y(_0052_)
  );
  NAND _1471_ (
    .A(reset),
    .B(\mem[4] [3]),
    .Y(_0723_)
  );
  NAND _1472_ (
    .A(_0564_),
    .B(_0710_),
    .Y(_0724_)
  );
  NOR _1473_ (
    .A(_0710_),
    .B(_0723_),
    .Y(_0725_)
  );
  NOT _1474_ (
    .A(_0725_),
    .Y(_0726_)
  );
  NAND _1475_ (
    .A(_0724_),
    .B(_0726_),
    .Y(_0053_)
  );
  NAND _1476_ (
    .A(reset),
    .B(\mem[4] [4]),
    .Y(_0727_)
  );
  NAND _1477_ (
    .A(_0569_),
    .B(_0710_),
    .Y(_0728_)
  );
  NOR _1478_ (
    .A(_0710_),
    .B(_0727_),
    .Y(_0729_)
  );
  NOT _1479_ (
    .A(_0729_),
    .Y(_0730_)
  );
  NAND _1480_ (
    .A(_0728_),
    .B(_0730_),
    .Y(_0054_)
  );
  NAND _1481_ (
    .A(reset),
    .B(\mem[4] [5]),
    .Y(_0731_)
  );
  NAND _1482_ (
    .A(_0574_),
    .B(_0710_),
    .Y(_0732_)
  );
  NOR _1483_ (
    .A(_0710_),
    .B(_0731_),
    .Y(_0733_)
  );
  NOT _1484_ (
    .A(_0733_),
    .Y(_0734_)
  );
  NAND _1485_ (
    .A(_0732_),
    .B(_0734_),
    .Y(_0055_)
  );
  NAND _1486_ (
    .A(reset),
    .B(\mem[4] [6]),
    .Y(_0735_)
  );
  NAND _1487_ (
    .A(_0579_),
    .B(_0710_),
    .Y(_0736_)
  );
  NOR _1488_ (
    .A(_0710_),
    .B(_0735_),
    .Y(_0737_)
  );
  NOT _1489_ (
    .A(_0737_),
    .Y(_0738_)
  );
  NAND _1490_ (
    .A(_0736_),
    .B(_0738_),
    .Y(_0056_)
  );
  NAND _1491_ (
    .A(reset),
    .B(\mem[4] [7]),
    .Y(_0739_)
  );
  NAND _1492_ (
    .A(_0584_),
    .B(_0710_),
    .Y(_0740_)
  );
  NOR _1493_ (
    .A(_0710_),
    .B(_0739_),
    .Y(_0741_)
  );
  NOT _1494_ (
    .A(_0741_),
    .Y(_0742_)
  );
  NAND _1495_ (
    .A(_0740_),
    .B(_0742_),
    .Y(_0057_)
  );
  NAND _1496_ (
    .A(reset),
    .B(\mem[4] [8]),
    .Y(_0743_)
  );
  NAND _1497_ (
    .A(_0589_),
    .B(_0710_),
    .Y(_0744_)
  );
  NOR _1498_ (
    .A(_0710_),
    .B(_0743_),
    .Y(_0745_)
  );
  NOT _1499_ (
    .A(_0745_),
    .Y(_0746_)
  );
  NAND _1500_ (
    .A(_0744_),
    .B(_0746_),
    .Y(_0058_)
  );
  NAND _1501_ (
    .A(reset),
    .B(\mem[4] [9]),
    .Y(_0747_)
  );
  NAND _1502_ (
    .A(_0594_),
    .B(_0710_),
    .Y(_0748_)
  );
  NOR _1503_ (
    .A(_0710_),
    .B(_0747_),
    .Y(_0749_)
  );
  NOT _1504_ (
    .A(_0749_),
    .Y(_0750_)
  );
  NAND _1505_ (
    .A(_0748_),
    .B(_0750_),
    .Y(_0059_)
  );
  NAND _1506_ (
    .A(reset),
    .B(\mem[4] [10]),
    .Y(_0751_)
  );
  NAND _1507_ (
    .A(_0599_),
    .B(_0710_),
    .Y(_0752_)
  );
  NOR _1508_ (
    .A(_0710_),
    .B(_0751_),
    .Y(_0753_)
  );
  NOT _1509_ (
    .A(_0753_),
    .Y(_0754_)
  );
  NAND _1510_ (
    .A(_0752_),
    .B(_0754_),
    .Y(_0049_)
  );
  NAND _1511_ (
    .A(reset),
    .B(\mem[4] [11]),
    .Y(_0755_)
  );
  NAND _1512_ (
    .A(_0604_),
    .B(_0710_),
    .Y(_0756_)
  );
  NOR _1513_ (
    .A(_0710_),
    .B(_0755_),
    .Y(_0757_)
  );
  NOT _1514_ (
    .A(_0757_),
    .Y(_0758_)
  );
  NAND _1515_ (
    .A(_0756_),
    .B(_0758_),
    .Y(_0050_)
  );
  NAND _1516_ (
    .A(wr_ptr[0]),
    .B(_0708_),
    .Y(_0759_)
  );
  NAND _1517_ (
    .A(reset),
    .B(\mem[5] [0]),
    .Y(_0760_)
  );
  NAND _1518_ (
    .A(_0759_),
    .B(_0760_),
    .Y(_0761_)
  );
  NOT _1519_ (
    .A(_0761_),
    .Y(_0762_)
  );
  NOR _1520_ (
    .A(_0549_),
    .B(_0759_),
    .Y(_0763_)
  );
  NOR _1521_ (
    .A(_0762_),
    .B(_0763_),
    .Y(_0060_)
  );
  NAND _1522_ (
    .A(reset),
    .B(\mem[5] [1]),
    .Y(_0764_)
  );
  NAND _1523_ (
    .A(_0759_),
    .B(_0764_),
    .Y(_0765_)
  );
  NOT _1524_ (
    .A(_0765_),
    .Y(_0766_)
  );
  NOR _1525_ (
    .A(_0554_),
    .B(_0759_),
    .Y(_0767_)
  );
  NOR _1526_ (
    .A(_0766_),
    .B(_0767_),
    .Y(_0063_)
  );
  NAND _1527_ (
    .A(reset),
    .B(\mem[5] [2]),
    .Y(_0768_)
  );
  NAND _1528_ (
    .A(_0759_),
    .B(_0768_),
    .Y(_0769_)
  );
  NOT _1529_ (
    .A(_0769_),
    .Y(_0770_)
  );
  NOR _1530_ (
    .A(_0559_),
    .B(_0759_),
    .Y(_0771_)
  );
  NOR _1531_ (
    .A(_0770_),
    .B(_0771_),
    .Y(_0064_)
  );
  NAND _1532_ (
    .A(reset),
    .B(\mem[5] [3]),
    .Y(_0772_)
  );
  NAND _1533_ (
    .A(_0759_),
    .B(_0772_),
    .Y(_0773_)
  );
  NOT _1534_ (
    .A(_0773_),
    .Y(_0774_)
  );
  NOR _1535_ (
    .A(_0564_),
    .B(_0759_),
    .Y(_0775_)
  );
  NOR _1536_ (
    .A(_0774_),
    .B(_0775_),
    .Y(_0065_)
  );
  NAND _1537_ (
    .A(reset),
    .B(\mem[5] [4]),
    .Y(_0776_)
  );
  NAND _1538_ (
    .A(_0759_),
    .B(_0776_),
    .Y(_0777_)
  );
  NOT _1539_ (
    .A(_0777_),
    .Y(_0778_)
  );
  NOR _1540_ (
    .A(_0569_),
    .B(_0759_),
    .Y(_0779_)
  );
  NOR _1541_ (
    .A(_0778_),
    .B(_0779_),
    .Y(_0066_)
  );
  NAND _1542_ (
    .A(reset),
    .B(\mem[5] [5]),
    .Y(_0780_)
  );
  NAND _1543_ (
    .A(_0759_),
    .B(_0780_),
    .Y(_0781_)
  );
  NOT _1544_ (
    .A(_0781_),
    .Y(_0782_)
  );
  NOR _1545_ (
    .A(_0574_),
    .B(_0759_),
    .Y(_0783_)
  );
  NOR _1546_ (
    .A(_0782_),
    .B(_0783_),
    .Y(_0067_)
  );
  NAND _1547_ (
    .A(reset),
    .B(\mem[5] [6]),
    .Y(_0784_)
  );
  NAND _1548_ (
    .A(_0759_),
    .B(_0784_),
    .Y(_0785_)
  );
  NOT _1549_ (
    .A(_0785_),
    .Y(_0786_)
  );
  NOR _1550_ (
    .A(_0579_),
    .B(_0759_),
    .Y(_0787_)
  );
  NOR _1551_ (
    .A(_0786_),
    .B(_0787_),
    .Y(_0068_)
  );
  NAND _1552_ (
    .A(reset),
    .B(\mem[5] [7]),
    .Y(_0788_)
  );
  NAND _1553_ (
    .A(_0759_),
    .B(_0788_),
    .Y(_0789_)
  );
  NOT _1554_ (
    .A(_0789_),
    .Y(_0790_)
  );
  NOR _1555_ (
    .A(_0584_),
    .B(_0759_),
    .Y(_0791_)
  );
  NOR _1556_ (
    .A(_0790_),
    .B(_0791_),
    .Y(_0069_)
  );
  NAND _1557_ (
    .A(reset),
    .B(\mem[5] [8]),
    .Y(_0792_)
  );
  NAND _1558_ (
    .A(_0759_),
    .B(_0792_),
    .Y(_0793_)
  );
  NOT _1559_ (
    .A(_0793_),
    .Y(_0794_)
  );
  NOR _1560_ (
    .A(_0589_),
    .B(_0759_),
    .Y(_0795_)
  );
  NOR _1561_ (
    .A(_0794_),
    .B(_0795_),
    .Y(_0070_)
  );
  NAND _1562_ (
    .A(reset),
    .B(\mem[5] [9]),
    .Y(_0796_)
  );
  NAND _1563_ (
    .A(_0759_),
    .B(_0796_),
    .Y(_0797_)
  );
  NOT _1564_ (
    .A(_0797_),
    .Y(_0798_)
  );
  NOR _1565_ (
    .A(_0594_),
    .B(_0759_),
    .Y(_0799_)
  );
  NOR _1566_ (
    .A(_0798_),
    .B(_0799_),
    .Y(_0071_)
  );
  NAND _1567_ (
    .A(reset),
    .B(\mem[5] [10]),
    .Y(_0800_)
  );
  NAND _1568_ (
    .A(_0759_),
    .B(_0800_),
    .Y(_0801_)
  );
  NOT _1569_ (
    .A(_0801_),
    .Y(_0802_)
  );
  NOR _1570_ (
    .A(_0599_),
    .B(_0759_),
    .Y(_0803_)
  );
  NOR _1571_ (
    .A(_0802_),
    .B(_0803_),
    .Y(_0061_)
  );
  NAND _1572_ (
    .A(reset),
    .B(\mem[5] [11]),
    .Y(_0804_)
  );
  NAND _1573_ (
    .A(_0759_),
    .B(_0804_),
    .Y(_0805_)
  );
  NOT _1574_ (
    .A(_0805_),
    .Y(_0806_)
  );
  NOR _1575_ (
    .A(_0604_),
    .B(_0759_),
    .Y(_0807_)
  );
  NOR _1576_ (
    .A(_0806_),
    .B(_0807_),
    .Y(_0062_)
  );
  NAND _1577_ (
    .A(reset),
    .B(_0546_),
    .Y(_0808_)
  );
  NOT _1578_ (
    .A(_0808_),
    .Y(_0809_)
  );
  NAND _1579_ (
    .A(_0213_),
    .B(_0215_),
    .Y(_0810_)
  );
  NOT _1580_ (
    .A(_0810_),
    .Y(_0811_)
  );
  NOR _1581_ (
    .A(_0808_),
    .B(_0810_),
    .Y(_0812_)
  );
  NAND _1582_ (
    .A(reset),
    .B(\mem[6] [0]),
    .Y(_0813_)
  );
  NAND _1583_ (
    .A(_0549_),
    .B(_0812_),
    .Y(_0814_)
  );
  NOR _1584_ (
    .A(_0812_),
    .B(_0813_),
    .Y(_0815_)
  );
  NOT _1585_ (
    .A(_0815_),
    .Y(_0816_)
  );
  NAND _1586_ (
    .A(_0814_),
    .B(_0816_),
    .Y(_0072_)
  );
  NAND _1587_ (
    .A(reset),
    .B(\mem[6] [1]),
    .Y(_0817_)
  );
  NAND _1588_ (
    .A(_0554_),
    .B(_0812_),
    .Y(_0818_)
  );
  NOR _1589_ (
    .A(_0812_),
    .B(_0817_),
    .Y(_0819_)
  );
  NOT _1590_ (
    .A(_0819_),
    .Y(_0820_)
  );
  NAND _1591_ (
    .A(_0818_),
    .B(_0820_),
    .Y(_0075_)
  );
  NAND _1592_ (
    .A(reset),
    .B(\mem[6] [2]),
    .Y(_0821_)
  );
  NAND _1593_ (
    .A(_0559_),
    .B(_0812_),
    .Y(_0822_)
  );
  NOR _1594_ (
    .A(_0812_),
    .B(_0821_),
    .Y(_0823_)
  );
  NOT _1595_ (
    .A(_0823_),
    .Y(_0824_)
  );
  NAND _1596_ (
    .A(_0822_),
    .B(_0824_),
    .Y(_0076_)
  );
  NAND _1597_ (
    .A(reset),
    .B(\mem[6] [3]),
    .Y(_0825_)
  );
  NAND _1598_ (
    .A(_0564_),
    .B(_0812_),
    .Y(_0826_)
  );
  NOR _1599_ (
    .A(_0812_),
    .B(_0825_),
    .Y(_0827_)
  );
  NOT _1600_ (
    .A(_0827_),
    .Y(_0828_)
  );
  NAND _1601_ (
    .A(_0826_),
    .B(_0828_),
    .Y(_0077_)
  );
  NAND _1602_ (
    .A(reset),
    .B(\mem[6] [4]),
    .Y(_0829_)
  );
  NAND _1603_ (
    .A(_0569_),
    .B(_0812_),
    .Y(_0830_)
  );
  NOR _1604_ (
    .A(_0812_),
    .B(_0829_),
    .Y(_0831_)
  );
  NOT _1605_ (
    .A(_0831_),
    .Y(_0832_)
  );
  NAND _1606_ (
    .A(_0830_),
    .B(_0832_),
    .Y(_0078_)
  );
  NAND _1607_ (
    .A(reset),
    .B(\mem[6] [5]),
    .Y(_0833_)
  );
  NAND _1608_ (
    .A(_0574_),
    .B(_0812_),
    .Y(_0096_)
  );
  NOR _1609_ (
    .A(_0812_),
    .B(_0833_),
    .Y(_0097_)
  );
  NOT _1610_ (
    .A(_0097_),
    .Y(_0098_)
  );
  NAND _1611_ (
    .A(_0096_),
    .B(_0098_),
    .Y(_0079_)
  );
  NAND _1612_ (
    .A(reset),
    .B(\mem[6] [6]),
    .Y(_0099_)
  );
  NOR _1613_ (
    .A(_0812_),
    .B(_0099_),
    .Y(_0100_)
  );
  NOT _1614_ (
    .A(_0100_),
    .Y(_0101_)
  );
  NAND _1615_ (
    .A(_0579_),
    .B(_0812_),
    .Y(_0102_)
  );
  NAND _1616_ (
    .A(_0101_),
    .B(_0102_),
    .Y(_0080_)
  );
  NAND _1617_ (
    .A(reset),
    .B(\mem[6] [7]),
    .Y(_0103_)
  );
  NAND _1618_ (
    .A(_0584_),
    .B(_0812_),
    .Y(_0104_)
  );
  NOR _1619_ (
    .A(_0812_),
    .B(_0103_),
    .Y(_0105_)
  );
  NOT _1620_ (
    .A(_0105_),
    .Y(_0106_)
  );
  NAND _1621_ (
    .A(_0104_),
    .B(_0106_),
    .Y(_0081_)
  );
  NAND _1622_ (
    .A(reset),
    .B(\mem[6] [8]),
    .Y(_0107_)
  );
  NAND _1623_ (
    .A(_0589_),
    .B(_0812_),
    .Y(_0108_)
  );
  NOR _1624_ (
    .A(_0812_),
    .B(_0107_),
    .Y(_0109_)
  );
  NOT _1625_ (
    .A(_0109_),
    .Y(_0110_)
  );
  NAND _1626_ (
    .A(_0108_),
    .B(_0110_),
    .Y(_0082_)
  );
  NAND _1627_ (
    .A(reset),
    .B(\mem[6] [9]),
    .Y(_0111_)
  );
  NAND _1628_ (
    .A(_0594_),
    .B(_0812_),
    .Y(_0112_)
  );
  NOR _1629_ (
    .A(_0812_),
    .B(_0111_),
    .Y(_0113_)
  );
  NOT _1630_ (
    .A(_0113_),
    .Y(_0114_)
  );
  NAND _1631_ (
    .A(_0112_),
    .B(_0114_),
    .Y(_0083_)
  );
  NAND _1632_ (
    .A(reset),
    .B(\mem[6] [10]),
    .Y(_0115_)
  );
  NAND _1633_ (
    .A(_0599_),
    .B(_0812_),
    .Y(_0116_)
  );
  NOR _1634_ (
    .A(_0812_),
    .B(_0115_),
    .Y(_0117_)
  );
  NOT _1635_ (
    .A(_0117_),
    .Y(_0118_)
  );
  NAND _1636_ (
    .A(_0116_),
    .B(_0118_),
    .Y(_0073_)
  );
  NAND _1637_ (
    .A(reset),
    .B(\mem[6] [11]),
    .Y(_0119_)
  );
  NAND _1638_ (
    .A(_0604_),
    .B(_0812_),
    .Y(_0120_)
  );
  NOR _1639_ (
    .A(_0812_),
    .B(_0119_),
    .Y(_0121_)
  );
  NOT _1640_ (
    .A(_0121_),
    .Y(_0122_)
  );
  NAND _1641_ (
    .A(_0120_),
    .B(_0122_),
    .Y(_0074_)
  );
  NOR _1642_ (
    .A(_0809_),
    .B(_0810_),
    .Y(_0123_)
  );
  NAND _1643_ (
    .A(_0808_),
    .B(_0811_),
    .Y(_0124_)
  );
  NAND _1644_ (
    .A(_0549_),
    .B(_0123_),
    .Y(_0125_)
  );
  NAND _1645_ (
    .A(\mem[7] [0]),
    .B(_0124_),
    .Y(_0126_)
  );
  NAND _1646_ (
    .A(_0125_),
    .B(_0126_),
    .Y(_0084_)
  );
  NAND _1647_ (
    .A(_0554_),
    .B(_0123_),
    .Y(_0127_)
  );
  NAND _1648_ (
    .A(\mem[7] [1]),
    .B(_0124_),
    .Y(_0128_)
  );
  NAND _1649_ (
    .A(_0127_),
    .B(_0128_),
    .Y(_0087_)
  );
  NAND _1650_ (
    .A(_0559_),
    .B(_0123_),
    .Y(_0129_)
  );
  NAND _1651_ (
    .A(\mem[7] [2]),
    .B(_0124_),
    .Y(_0130_)
  );
  NAND _1652_ (
    .A(_0129_),
    .B(_0130_),
    .Y(_0088_)
  );
  NAND _1653_ (
    .A(_0564_),
    .B(_0123_),
    .Y(_0131_)
  );
  NAND _1654_ (
    .A(\mem[7] [3]),
    .B(_0124_),
    .Y(_0132_)
  );
  NAND _1655_ (
    .A(_0131_),
    .B(_0132_),
    .Y(_0089_)
  );
  NAND _1656_ (
    .A(_0569_),
    .B(_0123_),
    .Y(_0133_)
  );
  NAND _1657_ (
    .A(\mem[7] [4]),
    .B(_0124_),
    .Y(_0134_)
  );
  NAND _1658_ (
    .A(_0133_),
    .B(_0134_),
    .Y(_0090_)
  );
  NAND _1659_ (
    .A(_0574_),
    .B(_0123_),
    .Y(_0135_)
  );
  NAND _1660_ (
    .A(\mem[7] [5]),
    .B(_0124_),
    .Y(_0136_)
  );
  NAND _1661_ (
    .A(_0135_),
    .B(_0136_),
    .Y(_0091_)
  );
  NAND _1662_ (
    .A(_0579_),
    .B(_0123_),
    .Y(_0137_)
  );
  NAND _1663_ (
    .A(\mem[7] [6]),
    .B(_0124_),
    .Y(_0138_)
  );
  NAND _1664_ (
    .A(_0137_),
    .B(_0138_),
    .Y(_0092_)
  );
  NAND _1665_ (
    .A(_0584_),
    .B(_0123_),
    .Y(_0139_)
  );
  NAND _1666_ (
    .A(\mem[7] [7]),
    .B(_0124_),
    .Y(_0140_)
  );
  NAND _1667_ (
    .A(_0139_),
    .B(_0140_),
    .Y(_0093_)
  );
  NAND _1668_ (
    .A(_0589_),
    .B(_0123_),
    .Y(_0141_)
  );
  NAND _1669_ (
    .A(\mem[7] [8]),
    .B(_0124_),
    .Y(_0142_)
  );
  NAND _1670_ (
    .A(_0141_),
    .B(_0142_),
    .Y(_0094_)
  );
  NAND _1671_ (
    .A(_0594_),
    .B(_0123_),
    .Y(_0143_)
  );
  NAND _1672_ (
    .A(\mem[7] [9]),
    .B(_0124_),
    .Y(_0144_)
  );
  NAND _1673_ (
    .A(_0143_),
    .B(_0144_),
    .Y(_0095_)
  );
  NAND _1674_ (
    .A(_0599_),
    .B(_0123_),
    .Y(_0145_)
  );
  NAND _1675_ (
    .A(\mem[7] [10]),
    .B(_0124_),
    .Y(_0146_)
  );
  NAND _1676_ (
    .A(_0145_),
    .B(_0146_),
    .Y(_0085_)
  );
  NAND _1677_ (
    .A(_0604_),
    .B(_0123_),
    .Y(_0147_)
  );
  NAND _1678_ (
    .A(\mem[7] [11]),
    .B(_0124_),
    .Y(_0148_)
  );
  NAND _1679_ (
    .A(_0147_),
    .B(_0148_),
    .Y(_0086_)
  );
  DFF _1680_ (
    .C(clk),
    .D(_0000_),
    .Q(\mem[0] [0])
  );
  DFF _1681_ (
    .C(clk),
    .D(_0003_),
    .Q(\mem[0] [1])
  );
  DFF _1682_ (
    .C(clk),
    .D(_0004_),
    .Q(\mem[0] [2])
  );
  DFF _1683_ (
    .C(clk),
    .D(_0005_),
    .Q(\mem[0] [3])
  );
  DFF _1684_ (
    .C(clk),
    .D(_0006_),
    .Q(\mem[0] [4])
  );
  DFF _1685_ (
    .C(clk),
    .D(_0007_),
    .Q(\mem[0] [5])
  );
  DFF _1686_ (
    .C(clk),
    .D(_0008_),
    .Q(\mem[0] [6])
  );
  DFF _1687_ (
    .C(clk),
    .D(_0009_),
    .Q(\mem[0] [7])
  );
  DFF _1688_ (
    .C(clk),
    .D(_0010_),
    .Q(\mem[0] [8])
  );
  DFF _1689_ (
    .C(clk),
    .D(_0011_),
    .Q(\mem[0] [9])
  );
  DFF _1690_ (
    .C(clk),
    .D(_0001_),
    .Q(\mem[0] [10])
  );
  DFF _1691_ (
    .C(clk),
    .D(_0002_),
    .Q(\mem[0] [11])
  );
  DFF _1692_ (
    .C(clk),
    .D(_0084_),
    .Q(\mem[7] [0])
  );
  DFF _1693_ (
    .C(clk),
    .D(_0087_),
    .Q(\mem[7] [1])
  );
  DFF _1694_ (
    .C(clk),
    .D(_0088_),
    .Q(\mem[7] [2])
  );
  DFF _1695_ (
    .C(clk),
    .D(_0089_),
    .Q(\mem[7] [3])
  );
  DFF _1696_ (
    .C(clk),
    .D(_0090_),
    .Q(\mem[7] [4])
  );
  DFF _1697_ (
    .C(clk),
    .D(_0091_),
    .Q(\mem[7] [5])
  );
  DFF _1698_ (
    .C(clk),
    .D(_0092_),
    .Q(\mem[7] [6])
  );
  DFF _1699_ (
    .C(clk),
    .D(_0093_),
    .Q(\mem[7] [7])
  );
  DFF _1700_ (
    .C(clk),
    .D(_0094_),
    .Q(\mem[7] [8])
  );
  DFF _1701_ (
    .C(clk),
    .D(_0095_),
    .Q(\mem[7] [9])
  );
  DFF _1702_ (
    .C(clk),
    .D(_0085_),
    .Q(\mem[7] [10])
  );
  DFF _1703_ (
    .C(clk),
    .D(_0086_),
    .Q(\mem[7] [11])
  );
  DFF _1704_ (
    .C(clk),
    .D(_0072_),
    .Q(\mem[6] [0])
  );
  DFF _1705_ (
    .C(clk),
    .D(_0075_),
    .Q(\mem[6] [1])
  );
  DFF _1706_ (
    .C(clk),
    .D(_0076_),
    .Q(\mem[6] [2])
  );
  DFF _1707_ (
    .C(clk),
    .D(_0077_),
    .Q(\mem[6] [3])
  );
  DFF _1708_ (
    .C(clk),
    .D(_0078_),
    .Q(\mem[6] [4])
  );
  DFF _1709_ (
    .C(clk),
    .D(_0079_),
    .Q(\mem[6] [5])
  );
  DFF _1710_ (
    .C(clk),
    .D(_0080_),
    .Q(\mem[6] [6])
  );
  DFF _1711_ (
    .C(clk),
    .D(_0081_),
    .Q(\mem[6] [7])
  );
  DFF _1712_ (
    .C(clk),
    .D(_0082_),
    .Q(\mem[6] [8])
  );
  DFF _1713_ (
    .C(clk),
    .D(_0083_),
    .Q(\mem[6] [9])
  );
  DFF _1714_ (
    .C(clk),
    .D(_0073_),
    .Q(\mem[6] [10])
  );
  DFF _1715_ (
    .C(clk),
    .D(_0074_),
    .Q(\mem[6] [11])
  );
  DFF _1716_ (
    .C(clk),
    .D(_0060_),
    .Q(\mem[5] [0])
  );
  DFF _1717_ (
    .C(clk),
    .D(_0063_),
    .Q(\mem[5] [1])
  );
  DFF _1718_ (
    .C(clk),
    .D(_0064_),
    .Q(\mem[5] [2])
  );
  DFF _1719_ (
    .C(clk),
    .D(_0065_),
    .Q(\mem[5] [3])
  );
  DFF _1720_ (
    .C(clk),
    .D(_0066_),
    .Q(\mem[5] [4])
  );
  DFF _1721_ (
    .C(clk),
    .D(_0067_),
    .Q(\mem[5] [5])
  );
  DFF _1722_ (
    .C(clk),
    .D(_0068_),
    .Q(\mem[5] [6])
  );
  DFF _1723_ (
    .C(clk),
    .D(_0069_),
    .Q(\mem[5] [7])
  );
  DFF _1724_ (
    .C(clk),
    .D(_0070_),
    .Q(\mem[5] [8])
  );
  DFF _1725_ (
    .C(clk),
    .D(_0071_),
    .Q(\mem[5] [9])
  );
  DFF _1726_ (
    .C(clk),
    .D(_0061_),
    .Q(\mem[5] [10])
  );
  DFF _1727_ (
    .C(clk),
    .D(_0062_),
    .Q(\mem[5] [11])
  );
  DFF _1728_ (
    .C(clk),
    .D(_0048_),
    .Q(\mem[4] [0])
  );
  DFF _1729_ (
    .C(clk),
    .D(_0051_),
    .Q(\mem[4] [1])
  );
  DFF _1730_ (
    .C(clk),
    .D(_0052_),
    .Q(\mem[4] [2])
  );
  DFF _1731_ (
    .C(clk),
    .D(_0053_),
    .Q(\mem[4] [3])
  );
  DFF _1732_ (
    .C(clk),
    .D(_0054_),
    .Q(\mem[4] [4])
  );
  DFF _1733_ (
    .C(clk),
    .D(_0055_),
    .Q(\mem[4] [5])
  );
  DFF _1734_ (
    .C(clk),
    .D(_0056_),
    .Q(\mem[4] [6])
  );
  DFF _1735_ (
    .C(clk),
    .D(_0057_),
    .Q(\mem[4] [7])
  );
  DFF _1736_ (
    .C(clk),
    .D(_0058_),
    .Q(\mem[4] [8])
  );
  DFF _1737_ (
    .C(clk),
    .D(_0059_),
    .Q(\mem[4] [9])
  );
  DFF _1738_ (
    .C(clk),
    .D(_0049_),
    .Q(\mem[4] [10])
  );
  DFF _1739_ (
    .C(clk),
    .D(_0050_),
    .Q(\mem[4] [11])
  );
  DFF _1740_ (
    .C(clk),
    .D(_0036_),
    .Q(\mem[3] [0])
  );
  DFF _1741_ (
    .C(clk),
    .D(_0039_),
    .Q(\mem[3] [1])
  );
  DFF _1742_ (
    .C(clk),
    .D(_0040_),
    .Q(\mem[3] [2])
  );
  DFF _1743_ (
    .C(clk),
    .D(_0041_),
    .Q(\mem[3] [3])
  );
  DFF _1744_ (
    .C(clk),
    .D(_0042_),
    .Q(\mem[3] [4])
  );
  DFF _1745_ (
    .C(clk),
    .D(_0043_),
    .Q(\mem[3] [5])
  );
  DFF _1746_ (
    .C(clk),
    .D(_0044_),
    .Q(\mem[3] [6])
  );
  DFF _1747_ (
    .C(clk),
    .D(_0045_),
    .Q(\mem[3] [7])
  );
  DFF _1748_ (
    .C(clk),
    .D(_0046_),
    .Q(\mem[3] [8])
  );
  DFF _1749_ (
    .C(clk),
    .D(_0047_),
    .Q(\mem[3] [9])
  );
  DFF _1750_ (
    .C(clk),
    .D(_0037_),
    .Q(\mem[3] [10])
  );
  DFF _1751_ (
    .C(clk),
    .D(_0038_),
    .Q(\mem[3] [11])
  );
  DFF _1752_ (
    .C(clk),
    .D(_0024_),
    .Q(\mem[2] [0])
  );
  DFF _1753_ (
    .C(clk),
    .D(_0027_),
    .Q(\mem[2] [1])
  );
  DFF _1754_ (
    .C(clk),
    .D(_0028_),
    .Q(\mem[2] [2])
  );
  DFF _1755_ (
    .C(clk),
    .D(_0029_),
    .Q(\mem[2] [3])
  );
  DFF _1756_ (
    .C(clk),
    .D(_0030_),
    .Q(\mem[2] [4])
  );
  DFF _1757_ (
    .C(clk),
    .D(_0031_),
    .Q(\mem[2] [5])
  );
  DFF _1758_ (
    .C(clk),
    .D(_0032_),
    .Q(\mem[2] [6])
  );
  DFF _1759_ (
    .C(clk),
    .D(_0033_),
    .Q(\mem[2] [7])
  );
  DFF _1760_ (
    .C(clk),
    .D(_0034_),
    .Q(\mem[2] [8])
  );
  DFF _1761_ (
    .C(clk),
    .D(_0035_),
    .Q(\mem[2] [9])
  );
  DFF _1762_ (
    .C(clk),
    .D(_0025_),
    .Q(\mem[2] [10])
  );
  DFF _1763_ (
    .C(clk),
    .D(_0026_),
    .Q(\mem[2] [11])
  );
  DFF _1764_ (
    .C(clk),
    .D(_0012_),
    .Q(\mem[1] [0])
  );
  DFF _1765_ (
    .C(clk),
    .D(_0015_),
    .Q(\mem[1] [1])
  );
  DFF _1766_ (
    .C(clk),
    .D(_0016_),
    .Q(\mem[1] [2])
  );
  DFF _1767_ (
    .C(clk),
    .D(_0017_),
    .Q(\mem[1] [3])
  );
  DFF _1768_ (
    .C(clk),
    .D(_0018_),
    .Q(\mem[1] [4])
  );
  DFF _1769_ (
    .C(clk),
    .D(_0019_),
    .Q(\mem[1] [5])
  );
  DFF _1770_ (
    .C(clk),
    .D(_0020_),
    .Q(\mem[1] [6])
  );
  DFF _1771_ (
    .C(clk),
    .D(_0021_),
    .Q(\mem[1] [7])
  );
  DFF _1772_ (
    .C(clk),
    .D(_0022_),
    .Q(\mem[1] [8])
  );
  DFF _1773_ (
    .C(clk),
    .D(_0023_),
    .Q(\mem[1] [9])
  );
  DFF _1774_ (
    .C(clk),
    .D(_0013_),
    .Q(\mem[1] [10])
  );
  DFF _1775_ (
    .C(clk),
    .D(_0014_),
    .Q(\mem[1] [11])
  );
  assign i = 32'd8;
endmodule

(* src = "readSynth.v:1" *)
module readSynth(clk, reset, fifoSynth_rd, rd_ptr);
  (* src = "readSynth.v:5" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "readSynth.v:2" *)
  input clk;
  (* src = "readSynth.v:2" *)
  input fifoSynth_rd;
  (* src = "readSynth.v:3" *)
  output [2:0] rd_ptr;
  (* src = "readSynth.v:2" *)
  input reset;
  NOT _17_ (
    .A(rd_ptr[1]),
    .Y(_16_)
  );
  NOT _18_ (
    .A(fifoSynth_rd),
    .Y(_01_)
  );
  NOT _19_ (
    .A(rd_ptr[2]),
    .Y(_02_)
  );
  NOT _20_ (
    .A(rd_ptr[0]),
    .Y(_03_)
  );
  NOR _21_ (
    .A(_01_),
    .B(_03_),
    .Y(_04_)
  );
  NAND _22_ (
    .A(fifoSynth_rd),
    .B(rd_ptr[0]),
    .Y(_05_)
  );
  NOR _23_ (
    .A(fifoSynth_rd),
    .B(rd_ptr[0]),
    .Y(_06_)
  );
  NOT _24_ (
    .A(_06_),
    .Y(_07_)
  );
  NAND _25_ (
    .A(reset),
    .B(_07_),
    .Y(_08_)
  );
  NOR _26_ (
    .A(_04_),
    .B(_08_),
    .Y(_00_[0])
  );
  NAND _27_ (
    .A(rd_ptr[1]),
    .B(_04_),
    .Y(_09_)
  );
  NOT _28_ (
    .A(_09_),
    .Y(_10_)
  );
  NAND _29_ (
    .A(_16_),
    .B(_05_),
    .Y(_11_)
  );
  NAND _30_ (
    .A(reset),
    .B(_11_),
    .Y(_12_)
  );
  NOR _31_ (
    .A(_10_),
    .B(_12_),
    .Y(_00_[1])
  );
  NOR _32_ (
    .A(_02_),
    .B(_09_),
    .Y(_13_)
  );
  NAND _33_ (
    .A(_02_),
    .B(_09_),
    .Y(_14_)
  );
  NAND _34_ (
    .A(reset),
    .B(_14_),
    .Y(_15_)
  );
  NOR _35_ (
    .A(_13_),
    .B(_15_),
    .Y(_00_[2])
  );
  (* src = "readSynth.v:5" *)
  DFF _36_ (
    .C(clk),
    .D(_00_[0]),
    .Q(rd_ptr[0])
  );
  (* src = "readSynth.v:5" *)
  DFF _37_ (
    .C(clk),
    .D(_00_[1]),
    .Q(rd_ptr[1])
  );
  (* src = "readSynth.v:5" *)
  DFF _38_ (
    .C(clk),
    .D(_00_[2]),
    .Q(rd_ptr[2])
  );
endmodule

(* src = "writeSynth.v:1" *)
module writeSynth(clk, reset, fifoSynth_wr, wr_ptr);
  (* src = "writeSynth.v:5" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "writeSynth.v:2" *)
  input clk;
  (* src = "writeSynth.v:2" *)
  input fifoSynth_wr;
  (* src = "writeSynth.v:2" *)
  input reset;
  (* src = "writeSynth.v:3" *)
  output [2:0] wr_ptr;
  NOT _17_ (
    .A(wr_ptr[1]),
    .Y(_16_)
  );
  NOT _18_ (
    .A(fifoSynth_wr),
    .Y(_01_)
  );
  NOT _19_ (
    .A(wr_ptr[2]),
    .Y(_02_)
  );
  NOT _20_ (
    .A(wr_ptr[0]),
    .Y(_03_)
  );
  NOR _21_ (
    .A(_01_),
    .B(_03_),
    .Y(_04_)
  );
  NAND _22_ (
    .A(fifoSynth_wr),
    .B(wr_ptr[0]),
    .Y(_05_)
  );
  NOR _23_ (
    .A(fifoSynth_wr),
    .B(wr_ptr[0]),
    .Y(_06_)
  );
  NOT _24_ (
    .A(_06_),
    .Y(_07_)
  );
  NAND _25_ (
    .A(reset),
    .B(_07_),
    .Y(_08_)
  );
  NOR _26_ (
    .A(_04_),
    .B(_08_),
    .Y(_00_[0])
  );
  NAND _27_ (
    .A(wr_ptr[1]),
    .B(_04_),
    .Y(_09_)
  );
  NOT _28_ (
    .A(_09_),
    .Y(_10_)
  );
  NAND _29_ (
    .A(_16_),
    .B(_05_),
    .Y(_11_)
  );
  NAND _30_ (
    .A(reset),
    .B(_11_),
    .Y(_12_)
  );
  NOR _31_ (
    .A(_10_),
    .B(_12_),
    .Y(_00_[1])
  );
  NOR _32_ (
    .A(_02_),
    .B(_09_),
    .Y(_13_)
  );
  NAND _33_ (
    .A(_02_),
    .B(_09_),
    .Y(_14_)
  );
  NAND _34_ (
    .A(reset),
    .B(_14_),
    .Y(_15_)
  );
  NOR _35_ (
    .A(_13_),
    .B(_15_),
    .Y(_00_[2])
  );
  (* src = "writeSynth.v:5" *)
  DFF _36_ (
    .C(clk),
    .D(_00_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "writeSynth.v:5" *)
  DFF _37_ (
    .C(clk),
    .D(_00_[1]),
    .Q(wr_ptr[1])
  );
  (* src = "writeSynth.v:5" *)
  DFF _38_ (
    .C(clk),
    .D(_00_[2]),
    .Q(wr_ptr[2])
  );
endmodule
