/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "mux2x1Synth.v:1" *)
module mux2x1Synth(clk, reset_L, selector, data_in0, data_in1, valid_0, valid_1, valid_out, data_out);
  (* src = "mux2x1Synth.v:27" *)
  wire [1:0] _00_;
  (* src = "mux2x1Synth.v:27" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "mux2x1Synth.v:3" *)
  input clk;
  (* src = "mux2x1Synth.v:6" *)
  input [1:0] data_in0;
  (* src = "mux2x1Synth.v:7" *)
  input [1:0] data_in1;
  (* src = "mux2x1Synth.v:10" *)
  output [1:0] data_out;
  (* src = "mux2x1Synth.v:4" *)
  input reset_L;
  (* src = "mux2x1Synth.v:5" *)
  input selector;
  (* src = "mux2x1Synth.v:8" *)
  input valid_0;
  (* src = "mux2x1Synth.v:8" *)
  input valid_1;
  (* src = "mux2x1Synth.v:9" *)
  output valid_out;
  NAND _25_ (
    .A(reset_L),
    .B(_20_),
    .Y(_21_)
  );
  NOR _26_ (
    .A(_19_),
    .B(_21_),
    .Y(_00_[1])
  );
  NOR _27_ (
    .A(reset_L),
    .B(valid_out),
    .Y(_22_)
  );
  NAND _28_ (
    .A(reset_L),
    .B(_09_),
    .Y(_23_)
  );
  NOT _29_ (
    .A(_23_),
    .Y(_24_)
  );
  NOR _30_ (
    .A(_22_),
    .B(_24_),
    .Y(_01_)
  );
  NOT _31_ (
    .A(data_out[1]),
    .Y(_02_)
  );
  NOT _32_ (
    .A(valid_0),
    .Y(_03_)
  );
  NOT _33_ (
    .A(selector),
    .Y(_04_)
  );
  NOT _34_ (
    .A(data_out[0]),
    .Y(_05_)
  );
  NAND _35_ (
    .A(valid_1),
    .B(selector),
    .Y(_06_)
  );
  NOT _36_ (
    .A(_06_),
    .Y(_07_)
  );
  NOR _37_ (
    .A(_03_),
    .B(selector),
    .Y(_08_)
  );
  NOR _38_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  NAND _39_ (
    .A(_04_),
    .B(data_in0[0]),
    .Y(_10_)
  );
  NAND _40_ (
    .A(selector),
    .B(data_in1[0]),
    .Y(_11_)
  );
  NAND _41_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  NOR _42_ (
    .A(_09_),
    .B(_12_),
    .Y(_13_)
  );
  NAND _43_ (
    .A(_05_),
    .B(_09_),
    .Y(_14_)
  );
  NAND _44_ (
    .A(reset_L),
    .B(_14_),
    .Y(_15_)
  );
  NOR _45_ (
    .A(_13_),
    .B(_15_),
    .Y(_00_[0])
  );
  NAND _46_ (
    .A(_04_),
    .B(data_in0[1]),
    .Y(_16_)
  );
  NAND _47_ (
    .A(selector),
    .B(data_in1[1]),
    .Y(_17_)
  );
  NAND _48_ (
    .A(_16_),
    .B(_17_),
    .Y(_18_)
  );
  NOR _49_ (
    .A(_09_),
    .B(_18_),
    .Y(_19_)
  );
  NAND _50_ (
    .A(_02_),
    .B(_09_),
    .Y(_20_)
  );
  (* src = "mux2x1Synth.v:27" *)
  DFF _51_ (
    .C(clk),
    .D(_01_),
    .Q(valid_out)
  );
  (* src = "mux2x1Synth.v:27" *)
  DFF _52_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_out[0])
  );
  (* src = "mux2x1Synth.v:27" *)
  DFF _53_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_out[1])
  );
endmodule
