/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "arbitro1Synth.v:1" *)
module arbitro1Synth(reset, clk, active, emptyFIFO, almost_fullFIFO, demuxin, pop, push);
  (* src = "arbitro1Synth.v:40" *)
  wire [2:0] _000_;
  (* src = "arbitro1Synth.v:40" *)
  wire [2:0] _001_;
  (* src = "arbitro1Synth.v:40" *)
  wire [2:0] _002_;
  (* src = "arbitro1Synth.v:40" *)
  wire [2:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  (* src = "arbitro1Synth.v:2" *)
  input active;
  (* src = "arbitro1Synth.v:4" *)
  input [3:0] almost_fullFIFO;
  (* src = "arbitro1Synth.v:2" *)
  input clk;
  (* src = "arbitro1Synth.v:9" *)
  wire [2:0] contadorP0;
  (* src = "arbitro1Synth.v:9" *)
  wire [2:0] contadorP1;
  (* src = "arbitro1Synth.v:9" *)
  wire [2:0] contadorP2;
  (* src = "arbitro1Synth.v:9" *)
  wire [2:0] contadorP3;
  (* src = "arbitro1Synth.v:5" *)
  input [11:0] demuxin;
  (* src = "arbitro1Synth.v:3" *)
  input [3:0] emptyFIFO;
  (* src = "arbitro1Synth.v:6" *)
  output [3:0] pop;
  (* src = "arbitro1Synth.v:7" *)
  output [3:0] push;
  (* src = "arbitro1Synth.v:2" *)
  input reset;
  NOT _108_ (
    .A(demuxin[8]),
    .Y(_067_)
  );
  NOT _109_ (
    .A(contadorP2[1]),
    .Y(_068_)
  );
  NOT _110_ (
    .A(contadorP0[0]),
    .Y(_069_)
  );
  NOT _111_ (
    .A(contadorP0[1]),
    .Y(_070_)
  );
  NOT _112_ (
    .A(contadorP0[2]),
    .Y(_071_)
  );
  NOT _113_ (
    .A(reset),
    .Y(_072_)
  );
  NOT _114_ (
    .A(emptyFIFO[2]),
    .Y(_073_)
  );
  NOR _115_ (
    .A(demuxin[10]),
    .B(demuxin[1]),
    .Y(_074_)
  );
  NOR _116_ (
    .A(demuxin[11]),
    .B(demuxin[0]),
    .Y(_075_)
  );
  NAND _117_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _118_ (
    .A(demuxin[4]),
    .B(demuxin[5]),
    .Y(_077_)
  );
  NOR _119_ (
    .A(demuxin[6]),
    .B(demuxin[7]),
    .Y(_078_)
  );
  NAND _120_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  NOT _121_ (
    .A(_079_),
    .Y(_080_)
  );
  NOR _122_ (
    .A(demuxin[9]),
    .B(demuxin[8]),
    .Y(_081_)
  );
  NOR _123_ (
    .A(demuxin[2]),
    .B(demuxin[3]),
    .Y(_082_)
  );
  NAND _124_ (
    .A(_081_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _125_ (
    .A(_076_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _126_ (
    .A(_080_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _127_ (
    .A(almost_fullFIFO[0]),
    .B(almost_fullFIFO[1]),
    .Y(_086_)
  );
  NOT _128_ (
    .A(_086_),
    .Y(_087_)
  );
  NOR _129_ (
    .A(almost_fullFIFO[2]),
    .B(almost_fullFIFO[3]),
    .Y(_088_)
  );
  NOT _130_ (
    .A(_088_),
    .Y(_089_)
  );
  NOR _131_ (
    .A(_087_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _132_ (
    .A(_086_),
    .B(_088_),
    .Y(_091_)
  );
  NAND _133_ (
    .A(active),
    .B(_085_),
    .Y(_092_)
  );
  NOR _134_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _135_ (
    .A(demuxin[9]),
    .B(_093_),
    .Y(_094_)
  );
  NOR _136_ (
    .A(_067_),
    .B(_094_),
    .Y(push[3])
  );
  NAND _137_ (
    .A(_081_),
    .B(_093_),
    .Y(_095_)
  );
  NOT _138_ (
    .A(_095_),
    .Y(push[0])
  );
  NOR _139_ (
    .A(demuxin[8]),
    .B(_094_),
    .Y(push[2])
  );
  NAND _140_ (
    .A(demuxin[8]),
    .B(_093_),
    .Y(_096_)
  );
  NOR _141_ (
    .A(demuxin[9]),
    .B(_096_),
    .Y(push[1])
  );
  NAND _142_ (
    .A(contadorP1[0]),
    .B(contadorP1[1]),
    .Y(_097_)
  );
  NOR _143_ (
    .A(contadorP1[2]),
    .B(emptyFIFO[1]),
    .Y(_098_)
  );
  NAND _144_ (
    .A(_097_),
    .B(_098_),
    .Y(_099_)
  );
  NOT _145_ (
    .A(_099_),
    .Y(_100_)
  );
  NOR _146_ (
    .A(contadorP0[2]),
    .B(emptyFIFO[0]),
    .Y(_101_)
  );
  NOT _147_ (
    .A(_101_),
    .Y(_102_)
  );
  NOR _148_ (
    .A(_091_),
    .B(_101_),
    .Y(_103_)
  );
  NAND _149_ (
    .A(_090_),
    .B(_102_),
    .Y(_104_)
  );
  NOR _150_ (
    .A(_099_),
    .B(_104_),
    .Y(_105_)
  );
  NAND _151_ (
    .A(_100_),
    .B(_103_),
    .Y(_106_)
  );
  NOR _152_ (
    .A(contadorP1[0]),
    .B(_105_),
    .Y(_107_)
  );
  NOR _153_ (
    .A(contadorP3[0]),
    .B(contadorP3[1]),
    .Y(_004_)
  );
  NOR _154_ (
    .A(contadorP3[2]),
    .B(emptyFIFO[3]),
    .Y(_005_)
  );
  NAND _155_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  NOT _156_ (
    .A(_006_),
    .Y(_007_)
  );
  NOR _157_ (
    .A(contadorP2[1]),
    .B(contadorP2[2]),
    .Y(_008_)
  );
  NOT _158_ (
    .A(_008_),
    .Y(_009_)
  );
  NOR _159_ (
    .A(emptyFIFO[2]),
    .B(_009_),
    .Y(_010_)
  );
  NAND _160_ (
    .A(_073_),
    .B(_008_),
    .Y(_011_)
  );
  NAND _161_ (
    .A(_006_),
    .B(_011_),
    .Y(_012_)
  );
  NAND _162_ (
    .A(_099_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _163_ (
    .A(contadorP1[0]),
    .B(_103_),
    .Y(_014_)
  );
  NOT _164_ (
    .A(_014_),
    .Y(_015_)
  );
  NAND _165_ (
    .A(_013_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _166_ (
    .A(reset),
    .B(_016_),
    .Y(_017_)
  );
  NOR _167_ (
    .A(_107_),
    .B(_017_),
    .Y(_001_[0])
  );
  NOR _168_ (
    .A(_099_),
    .B(_014_),
    .Y(_018_)
  );
  NOR _169_ (
    .A(contadorP1[1]),
    .B(_018_),
    .Y(_019_)
  );
  NOR _170_ (
    .A(_100_),
    .B(_104_),
    .Y(_020_)
  );
  NAND _171_ (
    .A(_099_),
    .B(_103_),
    .Y(_021_)
  );
  NOR _172_ (
    .A(_007_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _173_ (
    .A(_010_),
    .B(_021_),
    .Y(_023_)
  );
  NAND _174_ (
    .A(_011_),
    .B(_022_),
    .Y(_024_)
  );
  NAND _175_ (
    .A(reset),
    .B(_024_),
    .Y(_025_)
  );
  NOR _176_ (
    .A(_019_),
    .B(_025_),
    .Y(_001_[1])
  );
  NOR _177_ (
    .A(_091_),
    .B(_010_),
    .Y(_026_)
  );
  NOR _178_ (
    .A(_104_),
    .B(_012_),
    .Y(_027_)
  );
  NAND _179_ (
    .A(contadorP1[2]),
    .B(reset),
    .Y(_028_)
  );
  NOR _180_ (
    .A(_027_),
    .B(_028_),
    .Y(_001_[2])
  );
  NOR _181_ (
    .A(_101_),
    .B(_013_),
    .Y(_029_)
  );
  NAND _182_ (
    .A(contadorP3[0]),
    .B(_021_),
    .Y(_030_)
  );
  NOT _183_ (
    .A(_030_),
    .Y(_031_)
  );
  NOR _184_ (
    .A(_029_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _185_ (
    .A(contadorP3[0]),
    .B(_026_),
    .Y(_033_)
  );
  NOT _186_ (
    .A(_033_),
    .Y(_034_)
  );
  NAND _187_ (
    .A(reset),
    .B(_034_),
    .Y(_035_)
  );
  NOR _188_ (
    .A(_032_),
    .B(_035_),
    .Y(_003_[0])
  );
  NAND _189_ (
    .A(contadorP3[1]),
    .B(reset),
    .Y(_036_)
  );
  NOR _190_ (
    .A(_023_),
    .B(_036_),
    .Y(_003_[1])
  );
  NAND _191_ (
    .A(contadorP3[2]),
    .B(reset),
    .Y(_037_)
  );
  NOR _192_ (
    .A(_023_),
    .B(_037_),
    .Y(_003_[2])
  );
  NAND _193_ (
    .A(_010_),
    .B(_020_),
    .Y(_038_)
  );
  NAND _194_ (
    .A(contadorP2[0]),
    .B(_010_),
    .Y(_039_)
  );
  NOR _195_ (
    .A(_021_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _196_ (
    .A(contadorP2[0]),
    .B(_020_),
    .Y(_041_)
  );
  NOR _197_ (
    .A(contadorP2[0]),
    .B(_010_),
    .Y(_042_)
  );
  NOR _198_ (
    .A(_072_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _199_ (
    .A(_012_),
    .B(_039_),
    .Y(_044_)
  );
  NAND _200_ (
    .A(_020_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _201_ (
    .A(_043_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _202_ (
    .A(_041_),
    .B(_046_),
    .Y(_002_[0])
  );
  NOR _203_ (
    .A(_068_),
    .B(_022_),
    .Y(_047_)
  );
  NOR _204_ (
    .A(_040_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _205_ (
    .A(_072_),
    .B(_048_),
    .Y(_002_[1])
  );
  NAND _206_ (
    .A(contadorP2[2]),
    .B(reset),
    .Y(_049_)
  );
  NOR _207_ (
    .A(_022_),
    .B(_049_),
    .Y(_002_[2])
  );
  NOR _208_ (
    .A(_091_),
    .B(_102_),
    .Y(_050_)
  );
  NAND _209_ (
    .A(_090_),
    .B(_101_),
    .Y(_051_)
  );
  NAND _210_ (
    .A(_069_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _211_ (
    .A(contadorP0[0]),
    .B(_050_),
    .Y(_053_)
  );
  NOT _212_ (
    .A(_053_),
    .Y(_054_)
  );
  NAND _213_ (
    .A(_052_),
    .B(_053_),
    .Y(_055_)
  );
  NOR _214_ (
    .A(_025_),
    .B(_055_),
    .Y(_000_[0])
  );
  NAND _215_ (
    .A(_070_),
    .B(_053_),
    .Y(_056_)
  );
  NOR _216_ (
    .A(_070_),
    .B(_053_),
    .Y(_057_)
  );
  NAND _217_ (
    .A(contadorP0[1]),
    .B(_054_),
    .Y(_058_)
  );
  NAND _218_ (
    .A(_056_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _219_ (
    .A(_025_),
    .B(_059_),
    .Y(_000_[1])
  );
  NAND _220_ (
    .A(_090_),
    .B(_099_),
    .Y(_060_)
  );
  NOR _221_ (
    .A(_012_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _222_ (
    .A(_071_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _223_ (
    .A(_057_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _224_ (
    .A(_072_),
    .B(_063_),
    .Y(_000_[2])
  );
  NAND _225_ (
    .A(active),
    .B(reset),
    .Y(_064_)
  );
  NOR _226_ (
    .A(_051_),
    .B(_064_),
    .Y(pop[0])
  );
  NOR _227_ (
    .A(_106_),
    .B(_064_),
    .Y(pop[1])
  );
  NOR _228_ (
    .A(_038_),
    .B(_064_),
    .Y(pop[2])
  );
  NOR _229_ (
    .A(_006_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _230_ (
    .A(_023_),
    .B(_065_),
    .Y(_066_)
  );
  NOT _231_ (
    .A(_066_),
    .Y(pop[3])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _232_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contadorP0[0])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _233_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contadorP0[1])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _234_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contadorP0[2])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _235_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contadorP1[0])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _236_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contadorP1[1])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _237_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contadorP1[2])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _238_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contadorP2[0])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _239_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contadorP2[1])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _240_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contadorP2[2])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _241_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contadorP3[0])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _242_ (
    .C(clk),
    .D(_003_[1]),
    .Q(contadorP3[1])
  );
  (* src = "arbitro1Synth.v:40" *)
  DFF _243_ (
    .C(clk),
    .D(_003_[2]),
    .Q(contadorP3[2])
  );
endmodule
