/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "arbitro1Synth.v:1" *)
module arbitro1Synth(reset, clk, emptyFIFO, almost_fullFIFO, pop, push);
  (* src = "arbitro1Synth.v:36" *)
  wire [2:0] _000_;
  (* src = "arbitro1Synth.v:36" *)
  wire [2:0] _001_;
  (* src = "arbitro1Synth.v:36" *)
  wire [2:0] _002_;
  (* src = "arbitro1Synth.v:36" *)
  wire [2:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  (* src = "arbitro1Synth.v:4" *)
  input [3:0] almost_fullFIFO;
  (* src = "arbitro1Synth.v:2" *)
  input clk;
  (* src = "arbitro1Synth.v:8" *)
  wire [2:0] contadorpeso0;
  (* src = "arbitro1Synth.v:8" *)
  wire [2:0] contadorpeso1;
  (* src = "arbitro1Synth.v:8" *)
  wire [2:0] contadorpeso2;
  (* src = "arbitro1Synth.v:8" *)
  wire [2:0] contadorpeso3;
  (* src = "arbitro1Synth.v:3" *)
  input [3:0] emptyFIFO;
  (* src = "arbitro1Synth.v:5" *)
  output [3:0] pop;
  (* src = "arbitro1Synth.v:6" *)
  output [3:0] push;
  (* src = "arbitro1Synth.v:2" *)
  input reset;
  NOT _073_ (
    .A(contadorpeso2[0]),
    .Y(_019_)
  );
  NOT _074_ (
    .A(contadorpeso2[2]),
    .Y(_020_)
  );
  NOT _075_ (
    .A(reset),
    .Y(_021_)
  );
  NOT _076_ (
    .A(contadorpeso2[1]),
    .Y(_022_)
  );
  NOT _077_ (
    .A(contadorpeso0[1]),
    .Y(_023_)
  );
  NAND _078_ (
    .A(contadorpeso1[0]),
    .B(contadorpeso1[1]),
    .Y(_024_)
  );
  NOR _079_ (
    .A(contadorpeso1[2]),
    .B(_024_),
    .Y(_025_)
  );
  NOT _080_ (
    .A(_025_),
    .Y(_026_)
  );
  NOR _081_ (
    .A(contadorpeso1[2]),
    .B(_025_),
    .Y(_027_)
  );
  NOR _082_ (
    .A(almost_fullFIFO[0]),
    .B(almost_fullFIFO[1]),
    .Y(_028_)
  );
  NOR _083_ (
    .A(almost_fullFIFO[2]),
    .B(almost_fullFIFO[3]),
    .Y(_029_)
  );
  NAND _084_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  NOT _085_ (
    .A(_030_),
    .Y(_031_)
  );
  NOR _086_ (
    .A(emptyFIFO[0]),
    .B(emptyFIFO[1]),
    .Y(_032_)
  );
  NOR _087_ (
    .A(emptyFIFO[2]),
    .B(emptyFIFO[3]),
    .Y(_033_)
  );
  NAND _088_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NOT _089_ (
    .A(_034_),
    .Y(_035_)
  );
  NOR _090_ (
    .A(_030_),
    .B(_034_),
    .Y(_036_)
  );
  NAND _091_ (
    .A(_031_),
    .B(_035_),
    .Y(_037_)
  );
  NAND _092_ (
    .A(contadorpeso0[2]),
    .B(_036_),
    .Y(_038_)
  );
  NOR _093_ (
    .A(_027_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _094_ (
    .A(contadorpeso2[2]),
    .B(_022_),
    .Y(_040_)
  );
  NAND _095_ (
    .A(_020_),
    .B(contadorpeso2[1]),
    .Y(_041_)
  );
  NOR _096_ (
    .A(contadorpeso2[2]),
    .B(contadorpeso2[1]),
    .Y(_042_)
  );
  NOR _097_ (
    .A(contadorpeso3[1]),
    .B(contadorpeso3[2]),
    .Y(_043_)
  );
  NOR _098_ (
    .A(contadorpeso3[0]),
    .B(_021_),
    .Y(_044_)
  );
  NAND _099_ (
    .A(reset),
    .B(_043_),
    .Y(_045_)
  );
  NOR _100_ (
    .A(contadorpeso3[0]),
    .B(_045_),
    .Y(_046_)
  );
  NAND _101_ (
    .A(_043_),
    .B(_044_),
    .Y(_047_)
  );
  NOR _102_ (
    .A(_042_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _103_ (
    .A(_039_),
    .B(_048_),
    .Y(_049_)
  );
  NOT _104_ (
    .A(_049_),
    .Y(_003_[0])
  );
  NAND _105_ (
    .A(_039_),
    .B(_042_),
    .Y(_050_)
  );
  NAND _106_ (
    .A(_019_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _107_ (
    .A(_019_),
    .B(contadorpeso2[2]),
    .Y(_052_)
  );
  NAND _108_ (
    .A(_039_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _109_ (
    .A(contadorpeso2[1]),
    .B(_053_),
    .Y(_054_)
  );
  NAND _110_ (
    .A(_046_),
    .B(_051_),
    .Y(_055_)
  );
  NAND _111_ (
    .A(contadorpeso2[0]),
    .B(_039_),
    .Y(_056_)
  );
  NOR _112_ (
    .A(contadorpeso2[2]),
    .B(_056_),
    .Y(_057_)
  );
  NOR _113_ (
    .A(_054_),
    .B(_055_),
    .Y(_002_[0])
  );
  NOR _114_ (
    .A(contadorpeso2[1]),
    .B(_057_),
    .Y(_058_)
  );
  NOR _115_ (
    .A(_047_),
    .B(_058_),
    .Y(_002_[1])
  );
  NAND _116_ (
    .A(contadorpeso2[2]),
    .B(_046_),
    .Y(_059_)
  );
  NOT _117_ (
    .A(_059_),
    .Y(_002_[2])
  );
  NOR _118_ (
    .A(contadorpeso1[2]),
    .B(_038_),
    .Y(_060_)
  );
  NOR _119_ (
    .A(contadorpeso1[0]),
    .B(_060_),
    .Y(_061_)
  );
  NOT _120_ (
    .A(_061_),
    .Y(_062_)
  );
  NAND _121_ (
    .A(_046_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _122_ (
    .A(contadorpeso1[0]),
    .B(_060_),
    .Y(_064_)
  );
  NOT _123_ (
    .A(_064_),
    .Y(_065_)
  );
  NOR _124_ (
    .A(contadorpeso1[1]),
    .B(_064_),
    .Y(_066_)
  );
  NOR _125_ (
    .A(_063_),
    .B(_066_),
    .Y(_001_[0])
  );
  NOR _126_ (
    .A(contadorpeso1[1]),
    .B(_065_),
    .Y(_067_)
  );
  NOR _127_ (
    .A(_047_),
    .B(_067_),
    .Y(_001_[1])
  );
  NAND _128_ (
    .A(contadorpeso1[2]),
    .B(_046_),
    .Y(_068_)
  );
  NOT _129_ (
    .A(_068_),
    .Y(_001_[2])
  );
  NOR _130_ (
    .A(contadorpeso0[2]),
    .B(_037_),
    .Y(_069_)
  );
  NAND _131_ (
    .A(contadorpeso0[0]),
    .B(_069_),
    .Y(_070_)
  );
  NOR _132_ (
    .A(contadorpeso0[0]),
    .B(_069_),
    .Y(_071_)
  );
  NAND _133_ (
    .A(_046_),
    .B(_070_),
    .Y(_072_)
  );
  NOR _134_ (
    .A(_071_),
    .B(_072_),
    .Y(_000_[0])
  );
  NAND _135_ (
    .A(_023_),
    .B(_070_),
    .Y(_004_)
  );
  NAND _136_ (
    .A(_046_),
    .B(_004_),
    .Y(_005_)
  );
  NOR _137_ (
    .A(_023_),
    .B(_070_),
    .Y(_006_)
  );
  NAND _138_ (
    .A(contadorpeso0[0]),
    .B(contadorpeso0[1]),
    .Y(_007_)
  );
  NOR _139_ (
    .A(_037_),
    .B(_007_),
    .Y(_008_)
  );
  NOR _140_ (
    .A(_005_),
    .B(_006_),
    .Y(_000_[1])
  );
  NOR _141_ (
    .A(contadorpeso0[2]),
    .B(_008_),
    .Y(_009_)
  );
  NOR _142_ (
    .A(_047_),
    .B(_009_),
    .Y(_000_[2])
  );
  NAND _143_ (
    .A(_023_),
    .B(contadorpeso0[2]),
    .Y(_010_)
  );
  NOR _144_ (
    .A(contadorpeso0[0]),
    .B(_010_),
    .Y(_011_)
  );
  NAND _145_ (
    .A(reset),
    .B(_036_),
    .Y(_012_)
  );
  NOR _146_ (
    .A(_011_),
    .B(_012_),
    .Y(pop[0])
  );
  NAND _147_ (
    .A(_026_),
    .B(_011_),
    .Y(_013_)
  );
  NOR _148_ (
    .A(_012_),
    .B(_013_),
    .Y(pop[1])
  );
  NOR _149_ (
    .A(contadorpeso2[0]),
    .B(_041_),
    .Y(_014_)
  );
  NAND _150_ (
    .A(_019_),
    .B(_040_),
    .Y(_015_)
  );
  NAND _151_ (
    .A(_025_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _152_ (
    .A(_012_),
    .B(_016_),
    .Y(pop[2])
  );
  NAND _153_ (
    .A(contadorpeso3[0]),
    .B(_043_),
    .Y(_017_)
  );
  NAND _154_ (
    .A(_014_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _155_ (
    .A(_012_),
    .B(_018_),
    .Y(pop[3])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _156_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contadorpeso0[0])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _157_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contadorpeso0[1])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _158_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contadorpeso0[2])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _159_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contadorpeso1[0])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _160_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contadorpeso1[1])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _161_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contadorpeso1[2])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _162_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contadorpeso2[0])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _163_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contadorpeso2[1])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _164_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contadorpeso2[2])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _165_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contadorpeso3[0])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _166_ (
    .C(clk),
    .D(1'h0),
    .Q(contadorpeso3[1])
  );
  (* src = "arbitro1Synth.v:36" *)
  DFF _167_ (
    .C(clk),
    .D(1'h0),
    .Q(contadorpeso3[2])
  );
  assign _003_[2:1] = 2'h0;
  assign push = pop;
endmodule
