/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "mux2x1Synth.v:1" *)
module mux2x1Synth(clk, reset_L, selector, data_in0, data_in1, valid_0, valid_1, valid_out, data_out);
  (* src = "mux2x1Synth.v:22" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "mux2x1Synth.v:3" *)
  input clk;
  (* src = "mux2x1Synth.v:6" *)
  input [1:0] data_in0;
  (* src = "mux2x1Synth.v:7" *)
  input [1:0] data_in1;
  (* src = "mux2x1Synth.v:10" *)
  output [1:0] data_out;
  (* src = "mux2x1Synth.v:12" *)
  wire [1:0] min_0;
  (* src = "mux2x1Synth.v:12" *)
  wire [1:0] min_1;
  (* src = "mux2x1Synth.v:4" *)
  input reset_L;
  (* src = "mux2x1Synth.v:5" *)
  input selector;
  (* src = "mux2x1Synth.v:8" *)
  input valid_0;
  (* src = "mux2x1Synth.v:8" *)
  input valid_1;
  (* src = "mux2x1Synth.v:9" *)
  output valid_out;
  NOT _12_ (
    .A(min_1[0]),
    .Y(_01_)
  );
  NOT _13_ (
    .A(selector),
    .Y(_02_)
  );
  NOT _14_ (
    .A(min_1[1]),
    .Y(_03_)
  );
  NOR _15_ (
    .A(min_0[0]),
    .B(selector),
    .Y(_04_)
  );
  NAND _16_ (
    .A(_01_),
    .B(selector),
    .Y(_05_)
  );
  NAND _17_ (
    .A(reset_L),
    .B(_05_),
    .Y(_06_)
  );
  NOR _18_ (
    .A(_04_),
    .B(_06_),
    .Y(_00_[0])
  );
  NOR _19_ (
    .A(selector),
    .B(min_0[1]),
    .Y(_07_)
  );
  NAND _20_ (
    .A(selector),
    .B(_03_),
    .Y(_08_)
  );
  NAND _21_ (
    .A(reset_L),
    .B(_08_),
    .Y(_09_)
  );
  NOR _22_ (
    .A(_07_),
    .B(_09_),
    .Y(_00_[1])
  );
  NAND _23_ (
    .A(selector),
    .B(valid_1),
    .Y(_10_)
  );
  NAND _24_ (
    .A(_02_),
    .B(valid_0),
    .Y(_11_)
  );
  NAND _25_ (
    .A(_10_),
    .B(_11_),
    .Y(valid_out)
  );
  (* src = "mux2x1Synth.v:22" *)
  DFF _26_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_out[0])
  );
  (* src = "mux2x1Synth.v:22" *)
  DFF _27_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_out[1])
  );
  (* src = "mux2x1Synth.v:38" *)
  \$_DLATCH_P_  _28_ (
    .D(data_in1[0]),
    .E(valid_1),
    .Q(min_1[0])
  );
  (* src = "mux2x1Synth.v:38" *)
  \$_DLATCH_P_  _29_ (
    .D(data_in1[1]),
    .E(valid_1),
    .Q(min_1[1])
  );
  (* src = "mux2x1Synth.v:30" *)
  \$_DLATCH_P_  _30_ (
    .D(data_in0[0]),
    .E(valid_0),
    .Q(min_0[0])
  );
  (* src = "mux2x1Synth.v:30" *)
  \$_DLATCH_P_  _31_ (
    .D(data_in0[1]),
    .E(valid_0),
    .Q(min_0[1])
  );
endmodule
