/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "sumadorSynth.v:1" *)
module sumadorSynth(clk, reset, idx, data_A, data_B, sum_30_dd, idx_dd);
  (* src = "sumadorSynth.v:18" *)
  wire _000_;
  (* src = "sumadorSynth.v:18" *)
  wire [1:0] _001_;
  (* src = "sumadorSynth.v:18" *)
  wire [1:0] _002_;
  (* src = "sumadorSynth.v:18" *)
  wire [1:0] _003_;
  (* src = "sumadorSynth.v:18" *)
  wire [1:0] _004_;
  (* src = "sumadorSynth.v:43" *)
  wire [3:0] _005_;
  (* src = "sumadorSynth.v:43" *)
  wire [3:0] _006_;
  (* src = "sumadorSynth.v:43" *)
  wire [3:0] _007_;
  (* src = "sumadorSynth.v:18" *)
  wire [2:0] _008_;
  (* src = "sumadorSynth.v:18" *)
  wire [1:0] _009_;
  (* src = "sumadorSynth.v:18" *)
  wire [3:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  (* src = "sumadorSynth.v:11" *)
  wire acarreo_d;
  (* src = "sumadorSynth.v:2" *)
  input clk;
  (* src = "sumadorSynth.v:4" *)
  input [3:0] data_A;
  (* src = "sumadorSynth.v:9" *)
  wire [1:0] data_A_d;
  (* src = "sumadorSynth.v:7" *)
  wire [1:0] data_A_d_0;
  (* src = "sumadorSynth.v:4" *)
  input [3:0] data_B;
  (* src = "sumadorSynth.v:10" *)
  wire [1:0] data_B_d;
  (* src = "sumadorSynth.v:8" *)
  wire [1:0] data_B_d_0;
  (* src = "sumadorSynth.v:4" *)
  input [3:0] idx;
  (* src = "sumadorSynth.v:5" *)
  output [3:0] idx_dd;
  (* src = "sumadorSynth.v:15" *)
  wire [3:0] idx_etapa_1;
  (* src = "sumadorSynth.v:16" *)
  wire [3:0] idx_etapa_2;
  (* src = "sumadorSynth.v:3" *)
  input reset;
  (* src = "sumadorSynth.v:12" *)
  wire [2:0] sum_10;
  (* src = "sumadorSynth.v:13" *)
  wire [1:0] sum_10_d;
  (* src = "sumadorSynth.v:14" *)
  wire [3:0] sum_30_d;
  (* src = "sumadorSynth.v:5" *)
  output [3:0] sum_30_dd;
  NOT _069_ (
    .A(reset),
    .Y(_048_)
  );
  NOT _070_ (
    .A(data_A_d[1]),
    .Y(_049_)
  );
  NOT _071_ (
    .A(data_B_d[1]),
    .Y(_050_)
  );
  NOT _072_ (
    .A(acarreo_d),
    .Y(_051_)
  );
  NAND _073_ (
    .A(idx_etapa_1[1]),
    .B(reset),
    .Y(_052_)
  );
  NOT _074_ (
    .A(_052_),
    .Y(_007_[1])
  );
  NAND _075_ (
    .A(reset),
    .B(idx_etapa_1[2]),
    .Y(_053_)
  );
  NOT _076_ (
    .A(_053_),
    .Y(_007_[2])
  );
  NAND _077_ (
    .A(reset),
    .B(idx_etapa_1[3]),
    .Y(_054_)
  );
  NOT _078_ (
    .A(_054_),
    .Y(_007_[3])
  );
  NAND _079_ (
    .A(reset),
    .B(idx[0]),
    .Y(_055_)
  );
  NOT _080_ (
    .A(_055_),
    .Y(_006_[0])
  );
  NAND _081_ (
    .A(reset),
    .B(idx[1]),
    .Y(_056_)
  );
  NOT _082_ (
    .A(_056_),
    .Y(_006_[1])
  );
  NAND _083_ (
    .A(reset),
    .B(idx[2]),
    .Y(_057_)
  );
  NOT _084_ (
    .A(_057_),
    .Y(_006_[2])
  );
  NAND _085_ (
    .A(reset),
    .B(idx[3]),
    .Y(_058_)
  );
  NOT _086_ (
    .A(_058_),
    .Y(_006_[3])
  );
  NAND _087_ (
    .A(reset),
    .B(idx_etapa_2[0]),
    .Y(_059_)
  );
  NOT _088_ (
    .A(_059_),
    .Y(_005_[0])
  );
  NAND _089_ (
    .A(reset),
    .B(idx_etapa_2[1]),
    .Y(_060_)
  );
  NOT _090_ (
    .A(_060_),
    .Y(_005_[1])
  );
  NAND _091_ (
    .A(reset),
    .B(idx_etapa_2[2]),
    .Y(_061_)
  );
  NOT _092_ (
    .A(_061_),
    .Y(_005_[2])
  );
  NAND _093_ (
    .A(reset),
    .B(idx_etapa_2[3]),
    .Y(_062_)
  );
  NOT _094_ (
    .A(_062_),
    .Y(_005_[3])
  );
  NAND _095_ (
    .A(reset),
    .B(sum_10[0]),
    .Y(_063_)
  );
  NOT _096_ (
    .A(_063_),
    .Y(_009_[0])
  );
  NAND _097_ (
    .A(reset),
    .B(sum_10[1]),
    .Y(_064_)
  );
  NOT _098_ (
    .A(_064_),
    .Y(_009_[1])
  );
  NAND _099_ (
    .A(data_A_d[0]),
    .B(data_B_d[0]),
    .Y(_065_)
  );
  NOT _100_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _101_ (
    .A(data_A_d[0]),
    .B(data_B_d[0]),
    .Y(_067_)
  );
  NOT _102_ (
    .A(_067_),
    .Y(_068_)
  );
  NAND _103_ (
    .A(_065_),
    .B(_068_),
    .Y(_011_)
  );
  NOR _104_ (
    .A(_051_),
    .B(_011_),
    .Y(_012_)
  );
  NAND _105_ (
    .A(_051_),
    .B(_011_),
    .Y(_013_)
  );
  NAND _106_ (
    .A(reset),
    .B(_013_),
    .Y(_014_)
  );
  NOR _107_ (
    .A(_012_),
    .B(_014_),
    .Y(_010_[2])
  );
  NOR _108_ (
    .A(_066_),
    .B(_012_),
    .Y(_015_)
  );
  NOR _109_ (
    .A(_049_),
    .B(data_B_d[1]),
    .Y(_016_)
  );
  NOR _110_ (
    .A(data_A_d[1]),
    .B(_050_),
    .Y(_017_)
  );
  NOR _111_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NAND _112_ (
    .A(_015_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _113_ (
    .A(_015_),
    .B(_018_),
    .Y(_020_)
  );
  NAND _114_ (
    .A(reset),
    .B(_019_),
    .Y(_021_)
  );
  NOR _115_ (
    .A(_020_),
    .B(_021_),
    .Y(_010_[3])
  );
  NAND _116_ (
    .A(reset),
    .B(sum_10_d[0]),
    .Y(_022_)
  );
  NOT _117_ (
    .A(_022_),
    .Y(_010_[0])
  );
  NAND _118_ (
    .A(reset),
    .B(sum_10_d[1]),
    .Y(_023_)
  );
  NOT _119_ (
    .A(_023_),
    .Y(_010_[1])
  );
  NAND _120_ (
    .A(reset),
    .B(data_B_d_0[0]),
    .Y(_024_)
  );
  NOT _121_ (
    .A(_024_),
    .Y(_003_[0])
  );
  NAND _122_ (
    .A(reset),
    .B(data_B_d_0[1]),
    .Y(_025_)
  );
  NOT _123_ (
    .A(_025_),
    .Y(_003_[1])
  );
  NAND _124_ (
    .A(data_A[0]),
    .B(data_B[0]),
    .Y(_026_)
  );
  NOT _125_ (
    .A(_026_),
    .Y(_027_)
  );
  NOR _126_ (
    .A(data_A[0]),
    .B(data_B[0]),
    .Y(_028_)
  );
  NOT _127_ (
    .A(_028_),
    .Y(_029_)
  );
  NAND _128_ (
    .A(reset),
    .B(_029_),
    .Y(_030_)
  );
  NOR _129_ (
    .A(_027_),
    .B(_030_),
    .Y(_008_[0])
  );
  NAND _130_ (
    .A(data_A[1]),
    .B(data_B[1]),
    .Y(_031_)
  );
  NOT _131_ (
    .A(_031_),
    .Y(_032_)
  );
  NOR _132_ (
    .A(data_A[1]),
    .B(data_B[1]),
    .Y(_033_)
  );
  NOT _133_ (
    .A(_033_),
    .Y(_034_)
  );
  NAND _134_ (
    .A(_031_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _135_ (
    .A(_026_),
    .B(_035_),
    .Y(_036_)
  );
  NAND _136_ (
    .A(_026_),
    .B(_035_),
    .Y(_037_)
  );
  NAND _137_ (
    .A(reset),
    .B(_037_),
    .Y(_038_)
  );
  NOR _138_ (
    .A(_036_),
    .B(_038_),
    .Y(_008_[1])
  );
  NOR _139_ (
    .A(_032_),
    .B(_036_),
    .Y(_039_)
  );
  NOR _140_ (
    .A(_048_),
    .B(_039_),
    .Y(_008_[2])
  );
  NAND _141_ (
    .A(reset),
    .B(sum_10[2]),
    .Y(_040_)
  );
  NOT _142_ (
    .A(_040_),
    .Y(_000_)
  );
  NAND _143_ (
    .A(reset),
    .B(data_B[2]),
    .Y(_041_)
  );
  NOT _144_ (
    .A(_041_),
    .Y(_004_[0])
  );
  NAND _145_ (
    .A(reset),
    .B(data_B[3]),
    .Y(_042_)
  );
  NOT _146_ (
    .A(_042_),
    .Y(_004_[1])
  );
  NAND _147_ (
    .A(reset),
    .B(data_A_d_0[0]),
    .Y(_043_)
  );
  NOT _148_ (
    .A(_043_),
    .Y(_001_[0])
  );
  NAND _149_ (
    .A(reset),
    .B(data_A_d_0[1]),
    .Y(_044_)
  );
  NOT _150_ (
    .A(_044_),
    .Y(_001_[1])
  );
  NAND _151_ (
    .A(reset),
    .B(data_A[2]),
    .Y(_045_)
  );
  NOT _152_ (
    .A(_045_),
    .Y(_002_[0])
  );
  NAND _153_ (
    .A(reset),
    .B(data_A[3]),
    .Y(_046_)
  );
  NOT _154_ (
    .A(_046_),
    .Y(_002_[1])
  );
  NAND _155_ (
    .A(reset),
    .B(idx_etapa_1[0]),
    .Y(_047_)
  );
  NOT _156_ (
    .A(_047_),
    .Y(_007_[0])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _157_ (
    .C(clk),
    .D(_005_[0]),
    .Q(idx_dd[0])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _158_ (
    .C(clk),
    .D(_005_[1]),
    .Q(idx_dd[1])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _159_ (
    .C(clk),
    .D(_005_[2]),
    .Q(idx_dd[2])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _160_ (
    .C(clk),
    .D(_005_[3]),
    .Q(idx_dd[3])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _161_ (
    .C(clk),
    .D(_006_[0]),
    .Q(idx_etapa_1[0])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _162_ (
    .C(clk),
    .D(_006_[1]),
    .Q(idx_etapa_1[1])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _163_ (
    .C(clk),
    .D(_006_[2]),
    .Q(idx_etapa_1[2])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _164_ (
    .C(clk),
    .D(_006_[3]),
    .Q(idx_etapa_1[3])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _165_ (
    .C(clk),
    .D(_007_[0]),
    .Q(idx_etapa_2[0])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _166_ (
    .C(clk),
    .D(_007_[1]),
    .Q(idx_etapa_2[1])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _167_ (
    .C(clk),
    .D(_007_[2]),
    .Q(idx_etapa_2[2])
  );
  (* src = "sumadorSynth.v:43" *)
  DFF _168_ (
    .C(clk),
    .D(_007_[3]),
    .Q(idx_etapa_2[3])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _169_ (
    .C(clk),
    .D(_002_[0]),
    .Q(data_A_d_0[0])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _170_ (
    .C(clk),
    .D(_002_[1]),
    .Q(data_A_d_0[1])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _171_ (
    .C(clk),
    .D(_004_[0]),
    .Q(data_B_d_0[0])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _172_ (
    .C(clk),
    .D(_004_[1]),
    .Q(data_B_d_0[1])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _173_ (
    .C(clk),
    .D(_010_[0]),
    .Q(sum_30_dd[0])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _174_ (
    .C(clk),
    .D(_010_[1]),
    .Q(sum_30_dd[1])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _175_ (
    .C(clk),
    .D(_010_[2]),
    .Q(sum_30_dd[2])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _176_ (
    .C(clk),
    .D(_010_[3]),
    .Q(sum_30_dd[3])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _177_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_A_d[0])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _178_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_A_d[1])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _179_ (
    .C(clk),
    .D(_003_[0]),
    .Q(data_B_d[0])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _180_ (
    .C(clk),
    .D(_003_[1]),
    .Q(data_B_d[1])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _181_ (
    .C(clk),
    .D(_000_),
    .Q(acarreo_d)
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _182_ (
    .C(clk),
    .D(_008_[0]),
    .Q(sum_10[0])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _183_ (
    .C(clk),
    .D(_008_[1]),
    .Q(sum_10[1])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _184_ (
    .C(clk),
    .D(_008_[2]),
    .Q(sum_10[2])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _185_ (
    .C(clk),
    .D(_009_[0]),
    .Q(sum_10_d[0])
  );
  (* src = "sumadorSynth.v:18" *)
  DFF _186_ (
    .C(clk),
    .D(_009_[1]),
    .Q(sum_10_d[1])
  );
  assign sum_30_d = 4'h0;
endmodule
